### ISSUE TITLE
Android sends "code" as query parameter instead of body on the POST to swap URL

### ISSUE THREAD

**Issue by adebree** [lufinkey/react-native-spotify#10]
Previously the code parameter was send as POST body, but now is send as query parameter. Is this intended? Since this change breaks with your example php project which expects the parameter as $_POST (simply changing it on the PHP side to $_GET 'fixes' it, but not sure if this was your intention).

Previously:
http://xxx:8800/swap.php
Body:
code=...

Current master:
http://xxx:8800/swap.php?code=...
And no body

**Comment by lufinkey** [comment]
I will check up on this today

**Comment by lufinkey** [comment]
See if it works now. I think my latest commit should have fixed it. I think I really need to make a dev branch for large changes at this point...

**Comment by adebree** [comment]
Works, thanks.

You might want to make releases to npmjs.org and have the installation instructions point to the published release instead of having people use the master branch of your project.

**Comment by lufinkey** [comment]
I'm currently waiting on whether or not I can take over ownership of the
"react-native-spotify" package name that already exists in npm, but doesn't
support android. Once that gets resolved, I'll put it in npm

**Comment by robertoost** [comment]
Something is still wrong here, I updated and changed _GET back to _POST again, but now the app is not reaching the server at all. Reaching out to the server through the browser does still generate logs from the server, but pressing the login button results in a white screen now. I double checked my initialise variables, but they haven't changed since I last updated.

**Comment by lufinkey** [comment]
It seems the latest version of the module was having a null pointer exception when sending HTTP requests. This should be fixed now. Please try it and let me know.

**Comment by robertoost** [comment]
The null pointer exceptions and query parameter issues are both solved in the latest version, so this issue can be closed now. Thank you very much.

On another note, 
if it isn't possible to acquire the original name anytime soon, perhaps working with ```rn-spotify``` wouldn't be that bad. Just some food for thought.
