### ISSUE TITLE
Error on login page

### ISSUE THREAD

**Issue by DontStealMyCodePls** [lufinkey/react-native-spotify#100]
Well, I did initialized the app as you did in the example, although the state is set to true, when trying to log in the next error is shown:
![screenshot_1550329584](https://user-images.githubusercontent.com/46570907/52901547-a2df0800-320d-11e9-86e7-352a5a9848a1.png)

When calling `Spotify.isLoggedInAsync()`, the function is returning true and I am really confused.
Platform: Android

These are my Spotify options with the clientId censoured
![image](https://user-images.githubusercontent.com/46570907/52901569-f94c4680-320d-11e9-90d6-c03604d38894.png)

**Comment by lufinkey** [comment]
Are you sure you're awaiting the result of the promise that isLoggedInAsync returns?

**Comment by DontStealMyCodePls** [comment]
Hmmmm, strange, putting `await` in front of `Spotify.isLoggedInAsync()` is giving this error in chrome console
![image](https://user-images.githubusercontent.com/46570907/52902078-62cf5380-3214-11e9-8efc-7b51d9ac22b4.png)

**Comment by DontStealMyCodePls** [comment]
This is the whole `componentDidMount()`:
![image](https://user-images.githubusercontent.com/46570907/52902105-bcd01900-3214-11e9-9421-f5f8aa55b30f.png)

**Comment by lufinkey** [comment]
The code `if(Spotify.isInitializedAsync())` will always be `true` because `isInitializedAsync` is an async function and always returns a promise to a `boolean`, not an actual `boolean`. If you don't know how promises work, you can read up on them [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). The `await` keyword also can only be used inside an `async` function

Look at the way you're calling `Spotify.initialize`. You call `.then` and `.catch` after them because it's a promise that returns the `loggedIn` value or an `err` if it fails. You need to do the same with `Spotify.isInitializedAsync` and `Spotify.isLoggedInAsync`, or you need to use `async`/`await`

**Comment by DontStealMyCodePls** [comment]
Ooooh, got it, my bad then, I'll correct my code and come back with results, sorry for the trouble

**Comment by DontStealMyCodePls** [comment]
Managed to correct my code but now I ran into another error, it says that the clientId is missing, but I passed it to the module.
![image](https://user-images.githubusercontent.com/46570907/52903259-64ecde80-3223-11e9-862d-a20364221976.png)

**Comment by lufinkey** [comment]
Are you passing your client id into the initialize method?

**Comment by DontStealMyCodePls** [comment]
Yes
![image](https://user-images.githubusercontent.com/46570907/52903285-a8dfe380-3223-11e9-9bdf-f29fad2b0cd8.png)

**Comment by DontStealMyCodePls** [comment]
![image](https://user-images.githubusercontent.com/46570907/52903296-daf14580-3223-11e9-94a4-8028eb42f844.png)

**Comment by lufinkey** [comment]
Are you possibly calling initialize someplace else in the app before you call it here?

**Comment by lufinkey** [comment]
Oh... It's `clientID`. Not `clientId`. Please read the documentation

**Comment by lufinkey** [comment]
I'll update that error message

**Comment by DontStealMyCodePls** [comment]
Oh, ok, thanks.

**Comment by DontStealMyCodePls** [comment]
Oh, another one if I'm not bothering you. When I try to log in I receive this: 
![screenshot_1550343344](https://user-images.githubusercontent.com/46570907/52903919-599eb080-322d-11e9-9097-00314dd565ab.png)
And I think I know the issue but I'm not quite sure, in their documentation they are saying this:
![image](https://user-images.githubusercontent.com/46570907/52903938-8ce13f80-322d-11e9-817b-ec6f63c61e78.png)
But in AndroidManifest.xml I see nothing like it, so maybe this is causing the error?

**Comment by lufinkey** [comment]
You shouldn't need to add that. It should already be taken care of in the module. It's also very possible that the Spotify website is just having issues right now

**Comment by DontStealMyCodePls** [comment]
So should I try loging in later?

**Comment by lufinkey** [comment]
yeah

**Comment by DontStealMyCodePls** [comment]
Oh, ok thanks

**Comment by lufinkey** [comment]
I'd recommend you still try debugging the issue, but I have had this happen to me before where it was an error on Spotify's end

**Comment by DontStealMyCodePls** [comment]
I'll try debugging it but it's hard as I don't see the requests and what I'm receiving

**Comment by DontStealMyCodePls** [comment]
The login panel is still showing me an error even to this day.

**Comment by lufinkey** [comment]
Have you made sure to add your Android fingerprint to Spotify?

**Comment by DontStealMyCodePls** [comment]
Fingerprint? How do I add that?

**Comment by lufinkey** [comment]
[see this](https://developer.spotify.com/documentation/android/quick-start/#prepare-your-environment)

**Comment by lufinkey** [comment]
Actually that documentation is a bit spotty... Basically go to your app in the developer portal and make sure you've filled out all the fields with the correct values

**Comment by DontStealMyCodePls** [comment]
Oh ok, thanks, I'll try that and come back with results

**Comment by lufinkey** [comment]
I'm also not sure if you're allowed to have an underscore in the redirect URL scheme. Try using a callback URL without an underscore.

**Comment by DontStealMyCodePls** [comment]
I deleted the redirect url option from the object and the app crashes as I click login

**Comment by lufinkey** [comment]
Replace it.... don't delete it... :neutral_face:

Literally just go into the developer portal and make sure everything is filled out and matches your app, and don't use an underscore for your redirect URL. I'm not sure why you're just removing it.

**Comment by DontStealMyCodePls** [comment]
I just tried removing it to test, I'll try your way and come back with results :P

**Comment by DontStealMyCodePls** [comment]
Looks like everything is working fine but I receive an error that says my account is not premium. I guess they made the sdk this way and I can't do anything?

**Comment by lufinkey** [comment]
Oh...

PLEASE read the README next time. This module is only available for Spotify Premium users.
