### ISSUE TITLE
Could not find com.spotify.sdk:spotify-player-24-noconnect-2.20b:. Required by:project :app > project :rn-spotify-sdk

### ISSUE THREAD

**Issue by rizwan92** [lufinkey/react-native-spotify#104]
```
    "react-native": "^0.55.2",
    "rn-spotify-sdk": "^1.1.13",

```
i ran commmands

```
npm install --save rn-spotify-sdk
react-native link react-native-events
react-native link rn-spotify-sdk
```
and configure like this
```

flatDir {
			dirs project(':rn-spotify-sdk').file('libs'), 'libs'
		}
```

```
packagingOptions {
    pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
    pickFirst 'lib/x86/libgnustl_shared.so'
    exclude 'lib/arm64-v8a/libgnustl_shared.so'
    exclude 'lib/x86_64/libgnustl_shared.so'
}
```

```
...
import com.spotify.sdk.android.authentication.RNSpotifyPackage; // remove this line
import com.lufinkey.react.spotify.RNSpotifyPackage; // replace with this line
...
```

when i ran react-native run-android 

i get this error

`Could not find com.spotify.sdk:spotify-player-24-noconnect-2.20b:. Required by:project :app > project :rn-spotify-sdk `

**Comment by lufinkey** [comment]
No idea

**Comment by JakeMotta** [comment]
Re-read the installation notes carefully, and ensure that you've also included the following to your Module: app.
`    compile project(':rn-spotify-sdk')
`

If that doesn't work, I'd highly suggest downloading the sample project and comparing your project to the sample project setup.

**Comment by rizwan92** [comment]
yes i have this line in my /android/app/build.gradle file
![image](https://user-images.githubusercontent.com/19162978/53415960-7d65b180-39f8-11e9-99c3-bde468aeca54.png)

**Comment by lufinkey** [comment]
Have you tried using the example app? Does it work for you?

**Comment by rizwan92** [comment]
I tried example app it works fine just face simple small problem 
![image](https://user-images.githubusercontent.com/19162978/53426051-43060f80-3a0c-11e9-9706-a7fddfbb5513.png)

**Comment by lufinkey** [comment]
So the example app doesn't actually work then? I'm confused. Is this a separate issue you're reporting here with the example app or is that screenshot related to the issue you're facing in your app?

Please be more specific as to what this problem in your screenshot is and how you encountered it.

**Comment by rizwan92** [comment]
don't know why I was as getting this issue now I have solved it. but right now i am facing problem in initialization 
you have mentioned a redirect URL in your initialization method
like this 
`"redirectURL":"examplespotifyapp://auth",`
so i do like this 
"redirectURL":"com.myapp://auth",
 but it gives me error like this
![image](https://user-images.githubusercontent.com/19162978/53487374-72bb2300-3ab1-11e9-9816-2fd1af21c1c9.png)
and my cose snippet is 
![image](https://user-images.githubusercontent.com/19162978/53487466-aa29cf80-3ab1-11e9-81c7-77966c7b32b4.png)

**Comment by lufinkey** [comment]
Do you mind posting how you actually solved the problem so other people can figure it out if they run into the same thing?

**Comment by rizwan92** [comment]
at the very beginning it was saying could not find the library 
`api(name: 'spotify-android-auth-1.0.0', ext: 'aar')`
so convert this line  by this
`compile 'com.spotify.android:auth:1.1.0'` alter  the version form 1.0.0 to 1.1.0
then again its says did not find this library 
`api(name: 'spotify-player-24-noconnect-2.20b', ext: 'aar')
`
so i changed this line like this
`compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'
`
again it was saying did not find it. so i downloaded it from this [link](https://github.com/spotify/android-streaming-sdk/blob/6797753c9251334e14191b9ddae1b3c69496863c/spotify-player-24-noconnect-2.20b.aar)
and attached to the rn-spotify node modules form android studio it worked.
initializing and login was working after this

but then you give a reference of example repository hin rn-Spotify repo. I cloned it run it and log in using my credentials it worked. i was able to log in.

then i uninstall and unlink rn-spotify from my project removed it completely then i install it using yarn 
```
yarn add rn-spotify-sdk
react-native link react-native-events
react-native link rn-spotify-sdk
```
and followed the instructions very carefully mentioned in the repository

it worked I got no error then I placed the button and  on its  onPress I ran this code 

```
 onPress={async () => {
                  const isSpotifyInitialized = await Spotify.isInitializedAsync();
                  if (!isSpotifyInitialized) {
                    const spotifyOptions = {
                      clientID: "97bc7f6482994766a8dff66561e65c29",
                      sessionUserDefaultsKey: "SpotifySession",
                      redirectURL: "examplespotifyapp://auth",
                      scopes: [
                        "user-read-private",
                        "playlist-read",
                        "playlist-read-private",
                        "streaming"
                      ]
                    };
                    const loggedIn = await Spotify.initialize(spotifyOptions);
                    if (loggedIn) {
                      console.log("already logged int");
                    } else {
                      console.log("already not logged int making login");
                      Spotify.login()
                        .then(loggedIn => {
                          console.log(loggedIn);
                          if (loggedIn) {
                            // this.goToPlayer();
                          } else {
                            console.log("not logged int");
                          }
                        })
                        .catch(error => {
                          // error
                          Alert.alert("Error", error.message);
                        });
                    }
                  }
                }}
```
and gettign error like above comments

**Comment by rizwan92** [comment]
for more understanding i have recorded this [video](https://drive.google.com/open?id=1lVWs2AtGNJqWftSiNqK3o2InlcwCUyRV)

**Comment by lufinkey** [comment]
Since this error is fixed and you're getting a different error, I'm going to close this and keep the discussion in #75 since it's more relevant.
