### ISSUE TITLE
Can the streaming SDK be remote controlled?

### ISSUE THREAD

**Issue by liamtrampota** [lufinkey/react-native-spotify#105]
When the streaming SDK module is authorized, does it have a device_id that the spotify Api play and device route will register?

**Comment by lufinkey** [comment]
I don't believe so. My app doesn't seem to show up as a streamable device whenever I'm in the official Spotify app, so I would doubt it. However there might be some endpoint for it that I'm not aware of.

Since this isn't an actual issue, though, I'm going to close this.

**Comment by liamtrampota** [comment]
One way to check it would be to hit this endpoint: GET https://api.spotify.com/v1/me/player/devices. You could do so from here https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/. Unfortunately I'm still having issues install this module so I can't check it myself, but I'd be curious whether your app will show up as a spotify device.

**Comment by idanlo** [comment]
it does not show as a spotify device unfortunately (for me at least)
