### ISSUE TITLE
Trouble with Starting Rn-spotify project

### ISSUE THREAD

**Issue by KijanaG** [lufinkey/react-native-spotify#106]
Hey _lufinkey_ , the SDK that you created is super awesome! I'm not sure if you've experienced an issue similar to the one I'm experiencing though. I've linked the libraries, installed the ios-SDK and added the manual additions that were necessary. I'm still getting a linker command failed message when running building the iOS bundle for RN. Not sure what's going on, but I do not know to what extent I should be following all the Objective-C information in the Spotify ios-SDK setup...

Thanks,

KJ

**Comment by lufinkey** [comment]
It would be helpful if you posted the error you're getting 🙂

**Comment by KijanaG** [comment]
![screen shot 2019-03-03 at 10 42 46 pm](https://user-images.githubusercontent.com/37428103/53709699-9ced4780-3e07-11e9-8b87-81b7ae027288.png)

The issue is saying linked command failed. "ld: framework not found SpotifyAuthentication". I think the new Spotify SDK has a single framework, but since I cannot access these, I'm not sure if the other one will work with the react-native-spotify module...

Thanks

**Comment by KijanaG** [comment]
![screen shot 2019-03-03 at 10 39 49 pm](https://user-images.githubusercontent.com/37428103/53709798-1a18bc80-3e08-11e9-8226-5b63dd65269b.png)
![screen shot 2019-03-03 at 11 00 33 pm](https://user-images.githubusercontent.com/37428103/53709811-2bfa5f80-3e08-11e9-8ec0-4fe0c2909593.png)

**Comment by lufinkey** [comment]
Are you sure you added `../node_modules/rn-spotify-sdk/ios/external/SpotifySDK` to Framework Search Paths in your project settings?

**Comment by KijanaG** [comment]
![screen shot 2019-03-03 at 11 29 24 pm](https://user-images.githubusercontent.com/37428103/53710624-361e5d00-3e0c-11e9-9948-4b18f651b314.png)
Just added the Framework Search Paths and now I'm getting this Obj-C linker error.

**Comment by KijanaG** [comment]
It seems to be using the newest iOS SDK Download as well.

**Comment by KijanaG** [comment]
GOT IT!!!!! I deleted all traces of SpotifyiOS framework and yours worked seamlessly!

Thank You!

**Comment by lufinkey** [comment]
Yeah for future reference, you shouldn't need to download anything extra to get the library to work. It should all be in the module
