### ISSUE TITLE
Streaming breaks on token refresh

### ISSUE THREAD

**Issue by tgeorgy** [lufinkey/react-native-spotify#107]
react-native: 0.58.5,
rn-spotify-sdk: 1.2.0, 1.1.13
iOS

The player logs out and breaks the streaming when the token gets refreshed.
I set tokenRefreshEarliness to 3550 to hit the issue in 50 seconds after player starts.

**Comment by iMJumpmxn** [comment]
Same here!

**Comment by lufinkey** [comment]
Yep this is a bug with the native streaming SDK on iOS. I've been looking for a way around it, but there doesn't seem to be a built-in way. I may have to save the streaming state/metadata right before I refresh and then re-apply it

**Comment by lufinkey** [comment]
I'm pretty certain this is a native bug. Have you guys @tgeorgy @iMJumpmxn experienced this before those versions, or was it working correctly before?

**Comment by tgeorgy** [comment]
I've been using it since 1.1.8, I think, and always had the issue.

**Comment by lufinkey** [comment]
I've added the event `'sessionRenewed'` so you can potentially work around it for now. I'm eventually going to have to go with a hacky fix for this though.

**Comment by iMJumpmxn** [comment]
While fetching the new token i get this error : 
"Error: The operation couldn’t be completed. (NSURLErrorDomain error -1012.)"

**Comment by lufinkey** [comment]
Are you sure your token refresh server is up and accessible? That error means that the server couldn't be reached, I believe

**Comment by lufinkey** [comment]
[Here are the meanings behind the iOS error codes](https://stackoverflow.com/a/42434580)

**Comment by iMJumpmxn** [comment]
Thank you got it, but now i got the same problem with the music streaming if the token gets refreshed.

**Comment by lufinkey** [comment]
I've potentially fixed this issue in version `1.2.4`. Can you try that and see if it works for you?

**Comment by lufinkey** [comment]
note that you'll need to log out of spotify completely and re-login

**Comment by iMJumpmxn** [comment]
I checked it but the issue still exists

**Comment by lufinkey** [comment]
Did you completely log out of the app?

**Comment by iMJumpmxn** [comment]
Yes i log out, restarted my app, login with spotify again and the streaming still breaks if the token gets refreshed ....

**Comment by lufinkey** [comment]
Have you put logs in your token swap server to see what it's receiving and returning?

**Comment by iMJumpmxn** [comment]
Not at the moment but i listen to the sessionRenewed Event and it logs the new Token etc

**Comment by tgeorgy** [comment]
> Yes i log out, restarted my app, login with spotify again and the streaming still breaks if the token gets refreshed ....

Same for me. My current work around is to renew session on a track change.

**Comment by davidskaarup** [comment]
> > Yes i log out, restarted my app, login with spotify again and the streaming still breaks if the token gets refreshed ....
> 
> Same for me. My current work around is to renew session on a track change.

How did you implement this workaround? If I call renewSession on trackChange event the music stop playing right away.

**Comment by tgeorgy** [comment]
> > > Yes i log out, restarted my app, login with spotify again and the streaming still breaks if the token gets refreshed ....
> > 
> > 
> > Same for me. My current work around is to renew session on a track change.
> 
> How did you implement this workaround? If I call renewSession on trackChange event the music stop playing right away.

Well, I have my own queue, so I hit playURI everytime a song ends and now sometimes I do it with Spotify.renewSession().then(() => {playURI...}
But looks like it is not stable either, sometimes it doesn't start playing. I am still trying to figure out why, if it works out I will post a solution here.

**Comment by lufinkey** [comment]
I've added a fix to version `1.2.5` of this module. There's a short pause during refresh, but it resumes back to the same uri, index, and position. For now, I think that's the best fix that's going to happen, given that this is a bug in the native spotify streaming sdk.
