### ISSUE TITLE
Spotify module not accepting requests

### ISSUE THREAD

**Issue by KijanaG** [lufinkey/react-native-spotify#108]
Hello again,
I have been using the React-Native-Spotify module for a few days now while building an xcode/iOS application. For some reason I just started having an issue where a function would ignore my Spotify API call. For example, one minute it is retrieving and playing songs, and then next minute, it does not even console log a response from the API. I've reverted changes quite a few times so I don't think it is any specific call I am making, but do you have any thoughts on the matter? 
https://github.com/KijanaG/Tone/blob/master/RNTone/src/screens/Main/Main.js
I'm using React-Native v.16.6.3

Thank You,

KJ Garrett

**Comment by KijanaG** [comment]
If I delete the app and simulator and reboot everything it works. I'm just curious if I'm using the Spotify API correctly in my main.js file

**Comment by lufinkey** [comment]
Which API calls are not getting a response?

**Comment by lufinkey** [comment]
I've potentially fixed this issue. Can you completely log out of Spotify within your app, update the dependency to `1.2.4` and reinstall, and see if it's still happening?

**Comment by KijanaG** [comment]
Will Do! I Will get back to you as soon as I do it. I'm quite sure it was all on the main.js page, I have a series of calls in sequence, playURI -> MetaData -> isLoggedInAsync

**Comment by KijanaG** [comment]
It is working fine now, thank you!
