### ISSUE TITLE
AUTHENTICATION_SERVICE_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by srfaytkn** [lufinkey/react-native-spotify#109]
I upgraded the library today and i never made a change. spotify login screen started throw AUTHENTICATION_SERVICE_UNKNOWN_ERROR error

**Comment by lufinkey** [comment]
What version did you have previously, and what platform is this happening on?

**Comment by srfaytkn** [comment]
"1.1.13" -> "1.2.5" and android. also this error occurs if spotify is installed on the device

**Comment by lufinkey** [comment]
It sounds like your android app release sha1 fingerprint might not be updated in your spotify developer dashboard. Can you double check that?

**Comment by srfaytkn** [comment]
I checked it(release and debug). No problem.

**Comment by lufinkey** [comment]
I added a potential fix to the `master` branch. Can you see if this works for you?

**Comment by srfaytkn** [comment]
yes it's worked

**Comment by lufinkey** [comment]
Great. I've published a new release `1.2.6` which should have the fix.
