### ISSUE TITLE
Android: Getting stuck during login. "Cannot call showAuthActivity... " error#100

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#11]
An issue somewhat related to #4, if the initial login attempt goes wrong, the application cannot retry a login. Those who do try get greeted with a 100 error:

```
{code: 100, message: "Cannot call showAuthActivity while it is already being called", domain: "RCTSpotifyErrorDomain"}
```

While this can be prevented by fixing #4, the app does need to be reinstalled if this error is ever encountered. Reloading doesn't seem to work, so my workflow looks like this:

_Get a 105 error_ -> _Fix issue in code_ -> _Reload application_ -> _Get a 100 error_ -> _Rerun react-native run-android_ -> _Repeat if fix didn't work._

I find myself having to reinstall the app after every test.
Is this an issue with the Spotify SDK? Or is this something that can be fixed? It's concerning to me that any end-users might have to reinstall the app after their app fails to close the login screen correctly.

Does anyone else recognise the issue? Any tips?

**Comment by lufinkey** [comment]
It's sort of an issue with both. Basically the Spotify login function creates an Activity and shows it on top of the react native activity, so when you try to reload, it doesn't go away. I'll try to find a way to make it get rid of itself if you reload. It shouldn't require a reinstall to get rid of, though. You should just have to close the app in the background and restart it

**Comment by lufinkey** [comment]
It seems the latest version of the module was having a null pointer exception when sending HTTP requests. This should be fixed now. Please try it and let me know.

**Comment by robertoost** [comment]
Strange magic, I recall struggling with this a lot last week, but when I tested it, killing the app and starting it up again did the trick. It's weird, but I'm not complaining. I'll change the title of this issue to focus on the activity not getting rid of itself.

**Comment by lufinkey** [comment]
I haven't really found a good way around the inability to "refresh" the app while the login UIViewController or Activity is showing, so I'm going to go ahead and close this issue for now.
