### ISSUE TITLE
BUG - Could not invoke RNSpotify.playURI, error attempting to invoke virtual method - null object reference

### ISSUE THREAD

**Issue by idanlo** [lufinkey/react-native-spotify#110]
```
Could not invoke RNSpotify.playURI

null

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp-
ILpQm2EVIfQVY_HWNAHqe==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-
ILpQm2EVIfQVY_HWNAHqe==base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't 
find libgnustl_shared.so
```
when running on emulated android 9 with android studio it works just fine, running on my phone which is plugged in via usb does this error (my phone's android version is also 9)

platform: Android
react-native version: 0.59.1
rn-spotify-sdk version: 1.2.6

**Comment by idanlo** [comment]
Maybe this is also related. this happens when calling `Spotify.getSessionAsync()`
![image](https://user-images.githubusercontent.com/28350511/54695151-1b4d2780-4b32-11e9-93fc-770cb4d697f2.png)

**Comment by idanlo** [comment]
similar error happens when calling `Spotify.renewSession()`
![image](https://user-images.githubusercontent.com/28350511/54695218-3cae1380-4b32-11e9-96ff-32c27612455b.png)

**Comment by lufinkey** [comment]
Could you share some of the specs of the device it's running on? Specifically the architecture/processor. This sounds like a very ugly issue with the spotify sdk not linking correctly to one of the shared libraries, and I'm wondering if the architecture might not be supported.

**Comment by idanlo** [comment]
@lufinkey i think this is related to a problem i found regarding 64 bit android devices. take a look at [this](https://github.com/facebook/react-native/issues/2814) issue in the react-native repository. this was a problem for long time **but** it was fixed in the recent 0.59 react-native release. 
I'm new to react-native and I don't know much about linking native code with it but I think you need to update your react-native version to 0.59 or higher (current is 0.59.1)

**Comment by lufinkey** [comment]
React native is a peer dependency in this module, so you should be able to upgrade that separately without issue

**Comment by idanlo** [comment]
i am using react-native 0.59.1. still not working

**Comment by idanlo** [comment]
I somehow got it working.
My `android/app/build.gradle` file was like this 
```
packagingOptions {
        pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
        pickFirst 'lib/x86/libgnustl_shared.so'
        exclude 'lib/arm64-v8a/libgnustl_shared.so'
        exclude 'lib/x86_64/libgnustl_shared.so'
}
```
And I didn't understand why It's picking and then excluding and it had the file name in the error, so I removed the 2 `exclude` lines and now it's working! I guess this is not an issue with the library so I'll close the issue. Thanks for trying to help!

**Comment by lufinkey** [comment]
Interesting. Maybe I have to compile it for certain devices this way. I'm going to leave this issue open and experiment later.

**Comment by idanlo** [comment]
@lufinkey the other bugs i took a screenshot of still happen when I try to call `Spotify.getSessionAsync()` or `Spotify.renewSession()`

**Comment by lufinkey** [comment]
Could you open a new issue for that?
