### ISSUE TITLE
getPlaybackMetadata() is null after playURI

### ISSUE THREAD

**Issue by thebad77** [lufinkey/react-native-spotify#112]
Hello,

After playURI start the music I have this warning and I can't get the name or albumCoverArtURL .

![image](https://user-images.githubusercontent.com/32293500/54865580-91db6680-4d78-11e9-997d-88f5afb39303.png)

![image](https://user-images.githubusercontent.com/32293500/54865620-2e9e0400-4d79-11e9-9db5-2f1722c84911.png)

am I miss using the function getPlaybackMetadata() or is there a problem ? 
I tried getPlaybackMetadataAsync() and I have the same warning

Thank you.

**Comment by lufinkey** [comment]
Read the error message that popped up. `getPlaybackMetadata` gives null if the player is stopped, and you're accessing `currentTrack` on a null object. I'll update the README to mention this.

**Comment by thebad77** [comment]
what do I need to add for wait after playURI for get currentTrack() ?

**Comment by lufinkey** [comment]
Use the events

**Comment by thebad77** [comment]
Thank you.

For all those who have the same problem here is the solution

![image](https://user-images.githubusercontent.com/32293500/55073529-feb76f00-509e-11e9-938a-d5fe6e94bc98.png)

**Comment by burak4ydin** [comment]
getInfo(){
   Spotify.addListener('metadataChange', (arg1) => {
   console.log('arg1:' , arg1);
   console.log(Spotify.getPlaybackMetaData());
 });
 }

**Comment by lufinkey** [comment]
Try using the async version
