### ISSUE TITLE
playURI not playing music when app is in background

### ISSUE THREAD

**Issue by neilspurgeon** [lufinkey/react-native-spotify#114]
I'm having issues getting a song to play when my app is in background mode on iOS (haven't tested on Android).

I'm using a web socket connection to call playURI when the current track finishes. This works fine when the app is open, but audio never starts if it's in the background. I've already checked that playURI is being called and it fires successfully, just without audio.

I also have audio enabled in Background Modes and when I play a track normally and close it the audio works fine until it's time to call playURI again.

I'm guessing this has something to do with background mode permissions but am totally lost.

---

platform: iOS
react-native version: 0.57.8
rn-spotify-sdk version: 1.1.13

**Comment by lufinkey** [comment]
I had this issue and found that using `react-native-music-control` fixed this for me

**Comment by neilspurgeon** [comment]
That works! Thanks for the quick response.
