### ISSUE TITLE
loginWithSession on Android double resolve causes error

### ISSUE THREAD

**Issue by ririvas** [lufinkey/react-native-spotify#116]
I'm trying to use the **loginWithSession** endpoint on Android (and iOS eventually). I've successfully used **login**, **authenticate**, **logout**, **getSessionAsync**, and **search**. React-Native is 0.59.4

The call to **loginWithSession** kept failing and caused the application to shutdown. After running in Android Studio, I believe I was able to locate where the application errored out. The **Completion** instance passed into the **initializePlayerIfNeeded** method has the **resolve** method called twice, once by **initializePlayerIfNeeded** and once by the internal **onResolve** code.

I'm not using a token refresh server, merely trying to get this working for the one hour lifetime for now.

Please see below the code on the onResolve method:
`	

	public void loginWithSession(ReadableMap options, final Promise promise) {
		....
		final RNSpotifyModule module = this;
		initializePlayerIfNeeded(new Completion<Void>() {
			@Override
			public void onReject(SpotifyError error) {
				...
				error.reject(promise);
			}

			@Override
			public void onResolve(Void result) {
				boolean wasLoggedIn = module.loggedIn;
				...
				resolve(null); // CAUSE OF FAILURE
				if(!wasLoggedIn) {
					sendEvent("login", Convert.fromSessionData(auth.getSession()));
				}
			}
		});
	}`

After commenting out the resolve(null) line, I no longer ran into errors. Please let me know if I should include additional information or my code. 

Thanks

**Comment by lufinkey** [comment]
This should be fixed with version `1.2.7` in npm now
