### ISSUE TITLE
Is it possible to play local files?

### ISSUE THREAD

**Issue by davidskaarup** [lufinkey/react-native-spotify#117]
In the Spotify mobile app it's possible to download and play a playlist which contains local files which have been added via the Spotify desktop app.
When I load such a playlist with this module it lists the local files, but they are skipped when playing.
Is there any way to play local files via the SDK?

**Comment by lufinkey** [comment]
There's no download functionality in this module. It's specifically disallowed in the terms of service

**Comment by davidskaarup** [comment]
Ok, thanks for the clarification
