### ISSUE TITLE
 Please, I would like some help, I have not been able to obtain the user's Session data, I do not know how to do it, and how I can create the buttons to pause the audio

### ISSUE THREAD

**Issue by pulnec** [lufinkey/react-native-spotify#118]
Thank you for contributing to `rn-spotify-sdk`!

Be sure to include your react-native version, platform you're developing for, and iOS or Android version.

Please do not open issues about getting the module to work unless you have tried using both the example app and the example token swap server. Please make sure you have tried running on the latest react-native version before submitting a bug.

**Comment by lufinkey** [comment]
Please read the content of your issue and try again. I can't debug this issue unless you give me more information than just "I do not know how to do it".
