### ISSUE TITLE
Function Pause Tracks and NextTracks

### ISSUE THREAD

**Issue by pulnec** [lufinkey/react-native-spotify#119]
Hi, I've been running the component without problems so far, I only play the Playlist and the individual Tracks, as I can do to create a pause button and next track

**Comment by lufinkey** [comment]
Could you please be more descriptive about what you're doing and what error or issue you're having? I can't really understand what you mean.

Also please include the react native and module version like the issue template tells you to do when you submit.

**Comment by pulnec** [comment]
I hope to explain better this time, I have a project made with this **rn-spotify-sdk** component that has worked very well for me.

my question is the following as I can do with this component so that after I use the function "**Spotify.PlayUri ()**" to play the music, I can pause it in some way.

I want to create buttons in my project

Play -------> **Spotify.PlayUri ()**
Pause ----->. ??
Next Tracks ----> ??
Previus Tracks ----> ??

What function should I use to pause the music, and if I have a music list that I should use create a button to go to the next reproduction.

I hope you can understand me.

I have tried to use its function
**Spotify.sendRequest ()**

with the EndPoint that are on the Spotify developer page

GET | **/v1/me/player/currently-playing** | Get the User's Currently Playing Track
POST | **/v1/me/player/next** | Skip User's Playback To Next Track
POST | **/v1/me/player/previous** | Skip User's Playback To Previous Track
PUT | **/v1/me/player/pause** | Pause a User's Playback
PUT | **/v1/me/player/play** | Start/Resume a User's Playback

But I have not achieved the objective

**Comment by anker2000** [comment]
You should really read through the documentation. It's all described here: https://github.com/lufinkey/react-native-spotify – a simple search on the page for the word pause on that page would have gotten you the solution. 

Spotify.setPlaying(false), Spotify.skipToNext(), and Spotify.skipToPrevious() should do the trick.

**Comment by lufinkey** [comment]
Great, I'm going to go ahead and close this issue. @pulnec for future reference, please do as the README says and don't open issues without reading the documentation.
