### ISSUE TITLE
Android: Newest version doesn't reach the token server. error#105

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#12]
Something is still wrong here, I updated and changed _GET back to _POST again, but now the app is not reaching the server at all. I added some error logging to the php server at the start of the swap.php and refresh.php files. 

```
error_log( "SERVER REACHED" );
echo "Server reached";
```

Monitoring these logs during testing revealed some interesting stuff. 

Reaching out to the server _ip:port/swap.php_ or _refresh.php_ through the browser does generates logs from the server, but pressing the login button gives me no feedback in my logs, and the app is just stuck in a white screen now. I double checked my Spotify.initialize variables, but they haven't changed since I last updated.

```
	    "sessionUserDefaultsKey":"SpotifySession",
            "redirectURL":"ritualsspotifydevelop://callback",
            "scopes":["streaming", "user-read-playback-state","user-read-private", "user-modify-playback-state", "playlist-read-private"],
            "tokenSwapURL":"http://{ip address}:{port}/swap.php",
            "tokenRefreshURL":"http://{ip address}:{port}/refresh.php"
```

When I reverted back to 7de1c8c, the app could reach the server again. I'll remove the _POSTs and stick with the temporary _GET fix for now.

To be clear, I'm logging when the server gets approached in any way, shape or form. The browser triggers logs (```SERVER REACHED```) and shows the echo (```Server reached```) in the page, the 7de1c8c71450441b0fcd64a8fda3df0b2099ccda version of the app produces the same logs when I press login, it's just the new update that's giving me nothing ( and a blank screen ).

Do you have any idea what could be causing this?

**Comment by lufinkey** [comment]
It seems the latest version of the module was having a null pointer exception when sending HTTP requests. This should be fixed now. Please try it and let me know.

**Comment by robertoost** [comment]
Well, running 6cb5bd6b0e0a28eaf6882f30c53b0d9e1ac2306a seems to resolve the null pointer issue, and after testing the latest version 503510890c4b820acc4dd8d370a8a76a12756b38, I can confirm it all still works in that one too. Thank you very much!

In order to prevent any further update issues, I'll be sticking to this (hopefully) stable version of the module, and manually install any newer versions that I might find handy. I'll close this issue now, as it is resolved.

**Comment by lufinkey** [comment]
Yeah I have a dev branch now and a separate private test project, so we (hopefully) shouldn't run into as many issues now
