### ISSUE TITLE
Problem build release app -> react-native-events

### ISSUE THREAD

**Issue by pulnec** [lufinkey/react-native-spotify#120]
Hello I am compiling my application for production and I throw this error on the react-native-events, I do not understand much what would be the error check the android files and this is as the documentation says.

----------------------------------------------------------------------------------------------

> Task :react-native-events:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-events:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/nph/Documents/React/iveis_gym/node_modules/react-native-events/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/nph/Documents/React/iveis_gym/node_modules/react-native-events/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/nph/Documents/React/iveis_gym/node_modules/react-native-events/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /Users/nph/Documents/React/iveis_gym/node_modules/react-native-events/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by skeie** [comment]
Inside your `/android/build.gradle`, add this:

```
   subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = 28
                        buildToolsVersion = "28.0.3"
                    }
                }
        }
```

Add the end of `allprojects` clause

**Comment by pulnec** [comment]
Thanks skeie ! solved the problem.
