### ISSUE TITLE
Occasional crash on app start

### ISSUE THREAD

**Issue by sslash** [lufinkey/react-native-spotify#122]
Hey, thanks for making a great library.

I've been using this lib successfully for a while in production. But sometimes I get the following error when the app starts:

![image](https://user-images.githubusercontent.com/1174520/57706562-4487c100-7666-11e9-87e5-2398d5027a98.png)

React-native: 0.59.3
Platform: iOS,
iOS: 12.1

**Comment by lufinkey** [comment]
Are you making sure to initialize before you call any other functions?

**Comment by sslash** [comment]
I do fire of some spotify listeners at various places in the app, so yeah could be actually. Good call, I'll close this issue for now until I've come to a better conclusion!
