### ISSUE TITLE
Unable to play, got 3 arguments, expected 5

### ISSUE THREAD

**Issue by sschimmel** [lufinkey/react-native-spotify#123]
I've been able to initialize a player and login, get tracks etc. However when I try to play a track I get this error `RNSpotify.playURI got 3 arguments, expected 5`. 

Javascript code use is this: 
```
Spotify.playURI({
    spotifyURI: uri,
    startIndex: 0,
    startPosition: 0
  }).then(r => {
    console.log('Playing spotify', r);
  })
    .catch(err => {
    console.error(err);
  })
```

The uri is an uri of a track in Spotify: `spotify:track:3GCdLUSnKSMJhs4Tj6CV3s`.

I checked the Java code of playURI and it expects these 3 arguments plus a promise. That's 4 and not 5 arguments. I haven't been able to figure out what's causing this. 

I'm using `rn-spotify-sdk 1.2.6` and `react-native 0.59.3`. The error is on Android. Haven't started working on iOS yet. 

Error screenshot:
![image](https://user-images.githubusercontent.com/459456/58260419-ae931b00-7d76-11e9-9944-545ce97cee71.png)

**Comment by lufinkey** [comment]
You're passing the arguments as an object, rather than as parameters

**Comment by lufinkey** [comment]
Were you able to fix this?
