### ISSUE TITLE
INVALID_APP_ID ERROR

### ISSUE THREAD

**Issue by pulnec** [lufinkey/react-native-spotify#125]
I wanted to make a query even though I placed on the developer page of spotify the SHA1 code of the application in android as requested, I get the error of INVALID_APP_ID is there any additional configuration in the component? only happens on Android

**Comment by mynameisgan10** [comment]
Hi, could you clarify what you did? I'm stuck on the same problem, putting the SHA1 from the debug and from the google play does not work. Could you list out the steps you did to get the SHA1 from the google play console?

**Comment by pulnec** [comment]
Hello friend of course, in debugging you have no problems with the tests but in release if you have to add the SHA1, after you upload the application in the Google console control panel there is an option where it says “application signatures” there are you will find the correct SHA1 and is the one you will use in the spotify configuration

**Comment by mynameisgan10** [comment]
I used install ./gradlew installDebug and also pasted the debug SHA1 inside the Spotify dashboard and couldn't authenticate with my Spotify account inside my application on Android. It works fine on iOS. I have currently bypass this problem by uninstalling the Spotify Application on my iPhone and that seems to allow me to authenticate with my Spotify account inside my application.

**Comment by pulnec** [comment]
If you want to send me your whatsapp contact and I can help you better by sending you images of what you need to solve the problem send me jorgelandrade55@gmail.com
