### ISSUE TITLE
setShuffle doesn't do anything

### ISSUE THREAD

**Issue by sslash** [lufinkey/react-native-spotify#127]
React Native: 0.59.3
RN Spotify SDK: 1.2.9
platform: iOS.

I'm calling `setShuffle`, but every time I start playing a playlist, it doesn't shuffle.
I've tried calling `setShuffle` both before and after `Spotify.playURI(playlistId, 0, 0)`

**Comment by lufinkey** [comment]
Would you mind commenting on how you fixed this?

**Comment by sslash** [comment]
Yeah not sure when and how it happened, but it seems fine now. Sometimes it suddenly stops shuffling and I have to manually press shuffle again in the app where I use this lib. But that's good enough for me atm.
