### ISSUE TITLE
Cannot get local player context

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#13]
### The situation
I've been using sendRequest to get the current context that the player is streaming in. The "context", in this case, is the playlist, album, track, or list of tracks currently being played. The endpoint I'm sending GET requests to is ```v1/me/player.``` [(Get Information About The User’s Current Playback)](https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/)

The context object that I expect to receive:
```player.context```
```
"context": {
    "external_urls" : {
      "spotify" : "http://open.spotify.com/user/spotify/playlist/49znshcYJROspEqBoHg3Sv"
    },
    "href" : "https://api.spotify.com/v1/users/spotify/playlists/49znshcYJROspEqBoHg3Sv",
    "type" : "playlist",
    "uri" : "spotify:user:spotify:playlist:49znshcYJROspEqBoHg3Sv"
  }
```
### The problem
I want to know what context I'm in and if it matches the context that the player is supposed to be playing in. So far, I've been successfully controlling my other devices with Spotify Connect. When I have a session on a different device going on, I can get the current context just fine. It's when I start playback on the local player that everything falls apart.

Sending a GET request to ```v1/me/player``` while a local session is active produces an empty result. This makes me think that the local player context should gettable somewhere in the Android and iOS SDKs, although, I'm not so sure about all that. Is this possible locally?

**Comment by robertoost** [comment]
I've been digging a bit, and I might have found something interesting for the possible implementation of a ```getMetadata``` method.

### Android
It seems that the context uri I want to access is inside the [Metadata](https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/Metadata.html) object. It can be accessed with the [getMetadata](https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/Player.html#getMetadata--) method of the [SpotifyPlayer](https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/SpotifyPlayer.html) class.

### iOS
The same metadata is available on iOS inside the [SPTAudioStreamingController](https://spotify.github.io/ios-sdk/Classes/SPTAudioStreamingController.html), which has a nice [metadata](https://spotify.github.io/ios-sdk/Classes/SPTAudioStreamingController.html#//api/name/metadata) property. Looking at what I assume is the header for this class, it contains everything we might need.
```
@property (readonly, nonnull) NSString *name;
@property (readonly, nonnull) NSString *uri;
@property (readonly, nonnull) NSString *playbackSourceUri;
@property (readonly, nonnull) NSString *playbackSourceName;
@property (readonly, nonnull) NSString *artistName;
@property (readonly, nonnull) NSString *artistUri;
@property (readonly, nonnull) NSString *albumName;
@property (readonly, nonnull) NSString *albumUri;
```
Would you look at all those goodies. A getMetadata function would be a great addition to this module.

**Comment by robertoost** [comment]
Well I created an Android method ```getMetadata```, now to figure out the iOS version. I will be making a Pull Request if I pull it off.

**Comment by lufinkey** [comment]
There should be a method in the RCTSpotifyConvert class that returns a node friendly object from an SPTMetadata object

**Comment by lufinkey** [comment]
Added a getPlaybackMetadata method to the dev branch. Check and see if this works out for what you need

**Comment by robertoost** [comment]
I just tested yours on Android and it works splendidly. I should buy you a beer!

**Comment by lufinkey** [comment]
Feel free to Venmo me at @lufinkey if you'd like!
