### ISSUE TITLE
Session refresh_token is always null

### ISSUE THREAD

**Issue by iamraffe** [lufinkey/react-native-spotify#131]
Hi there! 

Great package you've got here.

I have an issue tho, it seems I am unable to get a refresh_token upon logging in / authenticating. 

I am setting swap & refresh urls during init process.

Everything else I've got working a-ok, this is the only thing that seems to be eluding me.

My react native version is 0.58.0. Right now I'm only developing using an android device, but will test soon using an iPhone.

I've set up the swap server following your example, however I'm still getting refresh_token null, and no evidence that my endpoints are even being hit.

Any pointers?

**Comment by lufinkey** [comment]
Are you using the same swap/refresh server as the example, or did you make your own following the example?

**Comment by iamraffe** [comment]
Thanks for getting back to me!

I've tried with the example and I've also tried with one I made on my own (which is in my actual server) that follows the example.

Maybe I am confused as to how the flow is supposed to go.

I am setting the tokenSwapUrl and tokenRefreshURL as options in the Spotify.initialize() method

Te response from initialize is a Session object similiar to this one

`{scopes: Array(6), expireTime: 1560778650673, refreshToken: null, accessToken: "BQAwng7fEmHFdzkYyvuQRACmXJiPjNM3PAUtdOQCBVJAZboBn-..._NrwetErCO2rlPA261DLxMkb4nTnvc4awUVtHTrSJsJJRhXow"}`

Is it expected for the refreshToken value to be null in this object after initialize is run?

If afterwards I attempt `await Spotify.renewSession()` I get false.

Lastly, there seems to be no indication that the server is actually being called at all. Not even to give an error.

Any ideas as to what I'm doing wrong throughout the process?

**Comment by lufinkey** [comment]
I'm very confused as to why you're even able to get an `accessToken` in the first place. You haven't called `Spotify.login`, right? As long as that hasn't been called, you shouldn't have a session at all.

**Comment by iamraffe** [comment]
Oh my bad. 

`Spotify.initialize()` simply returns `true`

I got confused by a `Spotify.loginWithSession(spotifySession)` that was occurring right after initialize.

**Comment by lufinkey** [comment]
So if you're calling `Spotify.loginWithSession`, you need to be passing it a refresh token, otherwise you're not gonna get one back. If you call `Spotofy.login`, it should take you through the flow and provide a refresh token at the end

**Comment by iamraffe** [comment]
My initial login func isn't returning a refresh_token either:

`    const spotifyOptions = {
      clientID: SPOTIFY_CLIENT_ID,
      sessionUserDefaultsKey: "SpotifySession",
      redirectURL: "peoople://auth",
      scopes: [
        "user-read-private",
        "playlist-read",
        "playlist-read-private",
        "streaming",
        "playlist-modify-public",
        "playlist-modify-private"
      ],
      showDialog: false,
      tokenSwapUrl: ${NODE_URL}api/users/spotify/swap
    };

    const spotifySession = await Spotify.authenticate(spotifyOptions).catch(
      error => {
        console.log("Error", error.message);
      }
    );`

This would be the initial "Connect to Spotify".

This is returning a Session object, which I'm storing so the user doesn't have to login next time he/she jumps in the app.

It is the second time he jumps in the app that I'm using the aforementioned `Spotify.loginWithSession(spotifySession)` (using the session from `Spotify.authenticate`)

However throughout the whole process, I can't get anything other than `refresh_token: null`

**Comment by lufinkey** [comment]
Okay first, you don't need to manually store your auth data. By setting `sessionUserDefaultsKey` in `Spotify.initialize`, the session data should automatically be saved and reloaded when the app loads again and calls `Spotify.initialize`

**Comment by lufinkey** [comment]
Second, can you post all the Spotify calls you're making? I have a feeling you're not passing the right data to the right functions

**Comment by iamraffe** [comment]
Ok here's the first thing upon app load:

```
 if (!(await Spotify.isInitializedAsync())) {
      const spotifyOptions = {
        clientID: SPOTIFY_CLIENT_ID,
        sessionUserDefaultsKey: "SpotifySession",
        redirectURL: "peoople://auth",
        scopes: [
          "user-read-private",
          "playlist-read",
          "playlist-read-private",
          "streaming",
          "playlist-modify-public",
          "playlist-modify-private"
        ],
        tokenSwapUrl: '${NODE_URL}api/users/spotify/swap',
        tokenRefreshURL: '${NODE_URL}api/users/spotify/refresh',
        tokenRefreshEarliness: 1800
      };

      await Spotify.initialize(spotifyOptions); // Which is returning either true or false
}
```

Then there's another view of the app, let's call ut UserSettings.js, where the user can connect/disconnect to/from his/her Spotify account.

Initially I was using:

```
    const spotifyOptions = {
      clientID: SPOTIFY_CLIENT_ID,
      sessionUserDefaultsKey: "SpotifySession",
      redirectURL: "peoople://auth",
      scopes: [
        "user-read-private",
        "playlist-read",
        "playlist-read-private",
        "streaming",
        "playlist-modify-public",
        "playlist-modify-private"
      ],
      showDialog: false,
      tokenSwapUrl: '${NODE_URL}api/users/spotify/swap'
    };
```

`await Spotify.login(spotifyOptions)`

But after an hour I would get kicked out. It was fine whilst I implemented all other features/functionality as I would just go to the UserSettings.js view and log in again.

So today the last piece of the puzzle is what I was implementing, which is session renewal. And this is where you find me.

**Comment by lufinkey** [comment]
So you actually don't need any of that information you're passing to `Spotify.login` except for `showDialog: false`. The rest of it is already passed to `Spotify.initialize` so those other values should already come from that. Try removing the extra data and see if it works

**Comment by iamraffe** [comment]
Ok so I removed all options except for `showDialog: false`.

I also switched back to using `Spotify.login()` instead of `Spotify.authenticate()`.

`Spotify.login()` returns `true`.

However, `Spotify.getSessionAsync()` returns 
```
{scopes: Array(6), expireTime: 1560784558754, refreshToken: null, accessToken: "BQADNLcBOQh-DznDsXLly8efhNJLjxbDerZwbaTS3ymEJOY1Lf…XzPtTPGAbC2msPmQhpFYq8a3hloUpQJcJpB-rsxSmt37yN6vA"}
``` 

And `Spotify.renewSession()`returns `false`

**Comment by lufinkey** [comment]
You spelled `tokenSwapURL` wrong. You used a lowercase Url

**Comment by lufinkey** [comment]
Make sure you logout before trying again

**Comment by lufinkey** [comment]
Feel free to venmo me if you'd like. My handle is @lufinkey

**Comment by iamraffe** [comment]
I'm in Madrid... Can't venmo sorry

**Comment by lufinkey** [comment]
No worries
