### ISSUE TITLE
Log in flow through Safari instead WebView

### ISSUE THREAD

**Issue by iamraffe** [lufinkey/react-native-spotify#132]
Hi there,

Would it be possible for the login flow to take place with Safari instead of with UIWebView? 

I am able to open the URL with Safari, but not sure how to handle the process back once the user has logged in in Safari.

Thanks!

**Comment by lufinkey** [comment]
You can use the [Linking](https://facebook.github.io/react-native/docs/linking) api to listen for the redirect URL and then use `loginWithSession` to login with the data manually. I won't officially support safari login though because it'd be more work to maintain.

**Comment by iamraffe** [comment]
Makes sense. Thanks for the idea! I'll try that tomorrow
