### ISSUE TITLE
does premium account required after the app release to end user?

### ISSUE THREAD

**Issue by AlohaDM** [lufinkey/react-native-spotify#133]
does the sdk still require premium account for the end use to use the spotify?

**Comment by lufinkey** [comment]
screenshot taken directly from the README
<img width="603" alt="Screen Shot 2019-06-21 at 9 00 03 AM" src="https://user-images.githubusercontent.com/7820113/59924132-0cad2f80-9403-11e9-8e57-9e18a1f62df9.png">
