### ISSUE TITLE
auto login without prompt login form

### ISSUE THREAD

**Issue by AlohaDM** [lufinkey/react-native-spotify#134]
is there any way to auto login to spotify using developer account without prompt out the login form?

**Comment by lufinkey** [comment]
I don't understand what you're asking?

**Comment by AlohaDM** [comment]
the example code inside the initialScreen, when press the login button will prompt out the spotify login form, is there anyway to by pass the login form? (eg, access it background to get authorization code to exchange access token), what im trying to achieve is, login without spotify login form.

**Comment by lufinkey** [comment]
no sorry I don't think this is possible. You can use `loginWithSession` if you already have an access token, both otherwise I don't see a way to go through the authorization flow without showing a login screen
