### ISSUE TITLE
Is there a way to get the refresh token

### ISSUE THREAD

**Issue by fhjbalfoort** [lufinkey/react-native-spotify#14]
I have a quick question.
Is there a way to get the refresh token out of the library?
I want to sent it to my API so i can store it for later use.

- Felix

**Comment by lufinkey** [comment]
I've added a getAuth method to the dev branch. Please let me know if this works for you and if you need any other data added to the Auth object

**Comment by lufinkey** [comment]
I've merged this feature into npm and the master
