### ISSUE TITLE
TypeError: null is not an object (evaluating 'nativeModule.__registerAsJSEventEmitter')

### ISSUE THREAD

**Issue by DoraJapin** [lufinkey/react-native-spotify#148]
I got an error in terminal like this,please help me how to solve this；thank you
![image](https://user-images.githubusercontent.com/20161208/67823017-6aadfa00-fafc-11e9-9e07-4bb99deab3ee.png)

**Comment by DoraJapin** [comment]
React Native: 0.61.2
RNSpotify: 1.2.12

**Comment by DoraJapin** [comment]
react-native-events 1.0.14

**Comment by lufinkey** [comment]
Would you mind commenting how you fixed this?

**Comment by weareyou-laurens** [comment]
If others experience a similar issue, it should be fixed when you add both these lines to your Pod file, and run 'pod install';

`
pod 'RNSpotify', :path => '../node_modules/rn-spotify-sdk'
pod 'RNEventEmitter', :path => '../node_modules/react-native-events'
`
