### ISSUE TITLE
I can not get react-native-events 1.0.15, I don't know why

### ISSUE THREAD

**Issue by DoraJapin** [lufinkey/react-native-spotify#149]
![image](https://user-images.githubusercontent.com/20161208/67826436-6cc98600-fb07-11e9-86dc-babfd0936b67.png)
![image](https://user-images.githubusercontent.com/20161208/67826538-c6ca4b80-fb07-11e9-9084-8013c57e1c99.png)
I use yarn add rn-spotify-sdk, I can got react-native-events 1.0.14
after run app, I got an error

**Comment by lufinkey** [comment]
Would you mind commenting how you fixed this?

**Comment by DoraJapin** [comment]
> Would you mind commenting how you fixed this?

I found react-native-events 1.0.15 from your git storehouse，repleace react-native-events from node-modules；but I don't know why I connot get 1.0.15; I use yarn install it, just can get 1.0.14
