### ISSUE TITLE
Enhancement: Event handling

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#15]
When a Spotify event occurs, the SDK fires events that would be very handy to have in any app that uses it. 

For example, I currently have to send Web API requests every few seconds to find out whether my Spotify connect session was paused on a different device. The music just stops and I can't give any visual confirmation that the session was paused until my Web API request confirms it.

Android
https://spotify.github.io/android-sdk/player/com/spotify/sdk/android/player/PlayerEvent.html

iOS
Under the protocol references, several delegates are defined.
https://spotify.github.io/ios-sdk/

Would it be possible to pass some callback methods to these events that execute when they fire?
Allowing developers to subscribe to these events would be a serious enhancement to this module.
As an added plus, it'd give the module an edge over the current npm package ```react-native-spotify```, which offers this functionality (but only on iOS!)

**Comment by lufinkey** [comment]
Yeah it would definitely be useful for the module to inherit from an EventEmitter. I'll look into doing it

**Comment by lufinkey** [comment]
I just finished making a [react-native-events](https://github.com/lufinkey/react-native-events) module to do this since the documented way is terrible and also global. I'll start adding events when I get the chance.

**Comment by robertoost** [comment]
That's great news! I'm looking forward to implementing them in the project I'm working on!

**Comment by sagark1510** [comment]
@lufinkey  Any updates on this issue?

**Comment by lufinkey** [comment]
Look at the [feature/events](https://github.com/lufinkey/react-native-spotify/tree/feature/events) branch for progress

**Comment by sagark1510** [comment]
@lufinkey Thanks for the prompt reply. Also I have another doubt if I can change the queued tracks?

**Comment by lufinkey** [comment]
Spotify hasn't added any functionality for this, unfortunately

On Feb 5, 2018 1:07 PM, "Sagar Khatri" <notifications@github.com> wrote:

@lufinkey <https://github.com/lufinkey> Thanks for the prompt reply. Also I
have another doubt if I can change the queued tracks?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lufinkey/react-native-spotify/issues/15#issuecomment-363169562>,
or mute the thread

**Comment by sagark1510** [comment]
oh ok. and what about clear the queue?

**Comment by lufinkey** [comment]
[no](https://github.com/spotify/ios-sdk/issues/488). Just look up if a particular feature is available for the Android and iOS SDK. If it isn't, it won't be available for this module either.

**Comment by sagark1510** [comment]
@lufinkey Thanks.

**Comment by lufinkey** [comment]
@sagark1510 If you have an issue with the feature/events branch, please post it here. It's just easier on me if we keep all issues within their threads.

**Comment by lufinkey** [comment]
So after some work on it last night, I believe that the [feature/events](https://github.com/lufinkey/react-native-spotify/tree/feature/events) branch should be stable now, if you want to try it out.

**Comment by donghee214** [comment]
It looks like the feature/events branch is down, I'm wondering if I could get my hands on those PlayerEvents!

**Comment by lufinkey** [comment]
The newest changes are on the dev branch

**Comment by donghee214** [comment]
A problem I'm encountering is that it's unable to find the path for :react-native-events.

I've tried installing react-native-events module within the react-native-spotify module however, i'm unable to run react-native link after installing it. It doesn't seem to detect react-native-spotify as a react native project.

Thanks!

**Comment by lufinkey** [comment]
You shouldn't have to install them separately. You should just be able to run
```
npm install --save "https://github.com/lufinkey/react-native-spotify#dev"
```
Are you sure your package.json is pointing to the dev branch?

**Comment by donghee214** [comment]
Ah, there's my mistake. Thank you once again!

**Comment by lufinkey** [comment]
Make sure you look at the dev branch's README, because it's different than the current README

**Comment by anker2000** [comment]
Thank you for all of this cool stuff! I was hoping you could help me shed some light on what could be causing this error:
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNEventEmitter", referenced from:
      objc-class-ref in libRCTSpotify.a(RCTSpotify.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by lufinkey** [comment]
That looks like react-native-events didn't get linked

**Comment by anker2000** [comment]
Ah, awesome - that solved it. Thanks! For some reason it had only linked the the Android version of react-native-events. Doing npm install react-native-events and running react-native link react-native-events again after fixed it.

**Comment by lufinkey** [comment]
The package has been rescoped and pushed to `rn-spotify-sdk` on npm
