### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by DoraJapin** [lufinkey/react-native-spotify#150]
when I run-android, it will report an error
![image](https://user-images.githubusercontent.com/20161208/67932275-86012e00-fbfe-11e9-9ef0-ac0014137ff6.png)
I use android studio to build, The same error occurs
![image](https://user-images.githubusercontent.com/20161208/67932385-c791d900-fbfe-11e9-94b1-c7e1fac2af4e.png)
I don't known why is there a lack of ‘import’ and ‘;’
gradle version 5.5
rn-spotify-sdk 1.2.12
rn 0.61.2

**Comment by DoraJapin** [comment]
![image](https://user-images.githubusercontent.com/20161208/67933156-3ae81a80-fc00-11e9-884f-270e1ad25947.png)
![image](https://user-images.githubusercontent.com/20161208/67933183-48050980-fc00-11e9-801e-a5f815b9b7fe.png)
![image](https://user-images.githubusercontent.com/20161208/67933203-50f5db00-fc00-11e9-8e7c-af6808654354.png)
configuration is ok

**Comment by DoraJapin** [comment]
![image](https://user-images.githubusercontent.com/20161208/67943962-43e3e680-fc16-11e9-987b-0c5e81c3734e.png)
I rebuild a project， same problem occurs
and when I react-native link rn-spolify-sdk, successed，but MainApplication.java generate it automatically
![image](https://user-images.githubusercontent.com/20161208/67944218-eac88280-fc16-11e9-9d42-18ba2fa46d3e.png)
Can you help me see where the problem is？
Thank you

**Comment by lufinkey** [comment]
🤷‍♂️

**Comment by sgeier** [comment]
Take a look at the react-native.config.js inside the rn-spotify-sdk directory under node_modules.
I added the import and ; on the line there, then it worked.

`module.exports = {
	dependency: {
		platforms: {
			android: {
				packageImportPath: 'import com.lufinkey.react.spotify.RNSpotifyPackage;'
			}
		}
	}
};
`

**Comment by lufinkey** [comment]
@grabbou made this PR. Was this a mistake? If so I'll update it

**Comment by Sagittarius8919** [comment]
@lufinkey Yes, this is a mistake. Could you update please:)
