### ISSUE TITLE
Possible to re-initialize a second time with more scope?

### ISSUE THREAD

**Issue by sslash** [lufinkey/react-native-spotify#151]
Is it possible to somehow re-initialize? If we need to ask the users for more scope at a later point in time after they have signed up? We ask the users to get their private podcast shows, but we don't want to ask that initially. 

When I try to initialize after the app has initialized I get this error `Error: Spotify has already been initialized`. Is there another way? I've tried logging out, but that didn't do it.

Greeeaaaaat library btw 💯💯

**Comment by lufinkey** [comment]
I think you would need to start a new session with different scopes. You could always trying using the `authenticate` method to authenticate a new session with different scopes and then `loginWithSession` to apply. You may need to call `logout` before `loginWithSession` although I'm not sure to be honest.

**Comment by sslash** [comment]
Thanks! I'll try that
