### ISSUE TITLE
Retrieve User's albums (inside Library). /v1/me/albums

### ISSUE THREAD

**Issue by sgeier** [lufinkey/react-native-spotify#154]
RN 62.4
Android / iOS
"rn-spotify-sdk": "^1.2.12",

Hello, 

from the docs as well as inside the source code I don't see a way to retrieve the User's Albums. 
@lufinkey can you confirm this?

I am referring to endpoint /v1/me/albums. It seems the package cannot retrieve that yet.

Thank you

**Comment by lufinkey** [comment]
You can use the `sendRequest` function documented in the README to send a generic request to the Spotify API. There are too many endpoints for me to bother adding all of them, so I just added the basic ones. If you need a specific one, you can use that function.
