### ISSUE TITLE
Are SDK actions rate-limited?

### ISSUE THREAD

**Issue by jayleeman12** [lufinkey/react-native-spotify#156]
Hello!
A little background: Up until a few days ago I was using the  official [spotify web api](https://developer.spotify.com/documentation/web-api/) without any external libraries.
Recently, I found out the web api's rate-limit is an issue for me (as in, I need to be able to send much more requests than what is allowed) - So I went out to look for a solution, and found out about spotify's [native SDK](https://developer.spotify.com/documentation/android/) , which I suspected has no rate limit - as it uses native process communication rather than web api requests.

So my question is: Is this package using the native SDK? And if so, is the SDK rate-limited?

**Comment by lufinkey** [comment]
I'm pretty sure it is yeah

**Comment by jayleeman12** [comment]
Thank you!
