### ISSUE TITLE
Using Android Autofill for signing in Spotify via Facebook closes login dialog and crashes the app

### ISSUE THREAD

**Issue by hbarylskyi** [lufinkey/react-native-spotify#158]
After I call Spotify.login(), Spotify login dialog opens. Then I tap 'Login with Facebook'. Login dialog redirects me to facebook login page. When I start typing my credentials there, Android system suggests to use the saved password. After I tap the email/password from the popup, dialog closes itself. After that, Spotify.login() returns Promise with `false`. If I call `Spotify.getSession` after that, the app crashes.

```
export const getSpotifySession = async () => {
  if (!Spotify.isInitialized()) {
    await Spotify.initialize({
      clientID: SPOTIFY_CLIENT_ID,
      redirectURL: REDIRECT_URL,
      scopes: [
        'user-read-email',
        'user-library-modify',
        'playlist-modify-private',
        'playlist-modify-public',
        'user-top-read',
      ],
      tokenSwapURL: SWAP_URL,
    });
  }

  if (!Spotify.isLoggedIn()) {
    const loggedInByUser = await Spotify.login(); // this is where the bug happens

    console.log(loggedInByUser) // -> false
  }

  return Spotify.getSession(); // crash happens here
};
```

<img width="417" alt="image" src="https://user-images.githubusercontent.com/12055535/71966544-d19c0d80-3227-11ea-9fa6-a8111e923caf.png">

react-native: 0.61.5
rn-spotify-sdk: ^1.2.12

**Comment by lufinkey** [comment]
Try using the async method. `getSessionAsync`. I know the synchronous methods tend to have issues in certain environments

**Comment by hbarylskyi** [comment]
@lufinkey thanks for replying. I'll try using `getSessionAsync`, but isn't the problem with `Spotify.login` method? Since this is the method that opens the login dialog.

**Comment by lufinkey** [comment]
Yeah I don't really know. Did it work, though?

**Comment by lufinkey** [comment]
Also if `Spotify.login` is returning `false`, that means the login was cancelled

**Comment by hbarylskyi** [comment]
Hey @lufinkey. Just tried `getSessionAsync`. Yes, it does not crash the app anymore. 

But it still does not resolve the issue. The main problem is that the login dialog closes itself. Which happens on `await Spotify.login();`.

p.s.: in production, our app wouldn't actually crash on `await getSession`. It's not called if `Spotify.login` returns false. I just noticed it while investigating the issue :)

**Comment by hbarylskyi** [comment]
Here's a screen recording:

![Untitled](https://user-images.githubusercontent.com/12055535/72367080-ee55ab00-3729-11ea-9477-24ec3a544c80.gif)

**Comment by lufinkey** [comment]
@hbarylskyi are you still having this issue?

**Comment by hbarylskyi** [comment]
@lufinkey we temporarily removed Spotify from our app. You can close for now, I will let you know if I experience it again.
