### ISSUE TITLE
Spotify.login() not redirecting properly after Facebook sign-in (React Native >.60, iOS)

### ISSUE THREAD

**Issue by ianlizzo** [lufinkey/react-native-spotify#159]
Hi all!

So I'm not sure if this has to do with the recent Spotify SDK changes, but after trying to use `Spotify.login()` with Facebook sign-in, it does not return a response/redirect after successfully logging into Facebook. It just takes me to the web view account page. This problem just recently started today. Here's a video:

![ezgif-6-1512a62d1f7d](https://user-images.githubusercontent.com/21691380/72570509-fae51b00-3871-11ea-9aeb-d5d4cfa802d9.gif)
 
Thanks for the help!

**Comment by lufinkey** [comment]
Is this possibly related to #158 ?

**Comment by ianlizzo** [comment]
@lufinkey That's what I was thinking too, they must be similar. Wonder if Spotify changed anything cause it was working up to a few days ago.

**Comment by sslash** [comment]
@ianlizzo did you get anywhere with this? I'm having a similar issue, though not the exact same. After I add my FB credentials it gets stuck on loading (https://github.com/lufinkey/react-native-spotify/issues/162)

**Comment by ianlizzo** [comment]
@sslash For some reason it fixed itself for me? But I figure I'd leave this up in case anyone else has the same issues. Might be on Spotify's end.
