### ISSUE TITLE
Installing using yarn doesn't pull in submodule of the Spotify SDK

### ISSUE THREAD

**Issue by adebree** [lufinkey/react-native-spotify#16]
Submodules aren't retrieved when using yarn for dependencies from github.

To reproduce:

```
yarn https://github.com/lufinkey/react-native-spotify
```

This results in an empty external/SpotifySDK directory:

```
ls node_modules/react-native-spotify/ios/external/SpotifySDK

{empty result}
```

While it contain the submodule when installed via npm:

```
ls node_modules/react-native-spotify/ios/external/SpotifySDK

CHANGELOG.md                    LICENSE                         SpotifyAuthentication.framework
Demo Projects                   README.md                       SpotifyMetadata.framework
ISSUE_TEMPLATE.md               SpotifyAudioPlayback.framework  docs
```

I found an issue describing this behaviour: https://github.com/yarnpkg/yarn/issues/1488 This issue also describes some workarounds, but they are all rather hackish. 

My understanding is that if you properly release the package in the NPM registry (and not install it directly from Github) this won't be a problem.

**Comment by lufinkey** [comment]
The package has been released in the NPM registry
https://www.npmjs.com/package/@lufinkey/react-native-spotify

**Comment by adebree** [comment]
Nice! Good to know, but unfortunately the released version doesn't work:

https://github.com/lufinkey/react-native-spotify/issues/17

**Comment by TimothePearce** [comment]
you should update the documentation to warn us about the use of `yarn` for this library. I had the same problem. Thanks anyway for your work 😄

**Comment by rgehan** [comment]
I'm working with @TimothePearce and were at first going to revert to using `npm`, but we then tried to install the module from `npm` instead of Github, and after linking the dependencies, it works properly!

**Comment by adebree** [comment]
Don't know if you targetting Android, in case be aware of: https://github.com/lufinkey/react-native-spotify/issues/28

**Comment by rgehan** [comment]
@adebree We'll look into this thanks
