### ISSUE TITLE
Spotify.login() returning "invalid client" error

### ISSUE THREAD

**Issue by trev91** [lufinkey/react-native-spotify#160]
On iOS, I've had no trouble with this module until about 3 days ago. I have not changed anything around the authorization flow, and when I call Spotify.login(), it launches the pop up window and allows me to fill out my spotify credentials, then asks if I want to grant access to the app, and when I confim, it closes the window and returns to my app with an ERROR.

The error is simply, "Invalid Client".

Again, no changes on my end, and my Spotify Developer Account is still live and functioning.

I thought I would set up another developer account with Spotify with a new client ID and try that, but I still get the same error.

Anybody else dealing with this issue?
`"rn-spotify-sdk": "^1.2.12"`
` "react-native": "0.61.2"`

**Comment by trev91** [comment]
This occurs whether I try to login via Facebook, or manually via Spotify.

**Comment by NeenaMishra12** [comment]
Hi @trev91 ,
Have you got any solution for this. I am also trying to integrate it in my application but, unable to get the hit on redirected url. 

@lufinkey Can you please suggest that why my redirect url is not getting hit? As I can get isLoggedIn = true but, still it is not getting hit.

**Comment by ganeshank** [comment]
I resolved this issue by adding the proper scopes.
"scopes":["user-read-private", "playlist-read", "playlist-read-private", "streaming"],

Use these scopes and try. 
I hope it will resolve for you.... :)

**Comment by IbrahimCanKALYA** [comment]
same error scopes wont fix the problem

**Comment by lufinkey** [comment]
Sounds like you're either missing the client Id or there's some info missing for your application in the spotify developer dashboard

**Comment by IbrahimCanKALYA** [comment]
@lufinkey thanks for quick response. I where right problem was redirectURI.
