### ISSUE TITLE
`framework not found SpotifyAudioPlayback` on Archive

### ISSUE THREAD

**Issue by biw** [lufinkey/react-native-spotify#163]
Hello,

react-native: `0.51.5`
platform: ios
ios: `13.2`

I am able to build correctly on the simulator, but when I go to Archive for export, I get the following error: 
```
ld: framework not found SpotifyAudioPlayback
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I feel like I'm missing something... any ideas? thanks!

**Comment by lufinkey** [comment]
Is your framework search path added to both the `Debug` and `Release` configurations?

**Comment by biw** [comment]
fixed, sorry to clog up your issues 😬 
for anyone else who reads this in the future: adding to the top-level framework search paths didn't work but adding it to both configs separately did. The UI on xcode was a little tricky
