### ISSUE TITLE
npmjs published library not working, missing ios-sdk

### ISSUE THREAD

**Issue by adebree** [lufinkey/react-native-spotify#17]
Problem becomes apparent when following the installation instruction until:

```
Manually add the Frameworks from node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK...
```

There is *no* external directory, so nothing to install:

![image](https://user-images.githubusercontent.com/478872/34724299-9aa3e9ce-f54d-11e7-90b7-6376f3dd88f6.png)

Trying to build the app without this step fails (of course) with: ```'SpotifyAuthentication/SpotifyAuthentication.h' file not found```

I've validated this with a fresh React Native app:

- Generated an app with ```react-native init rns```
- ```cd rns```
- ```npm install --save @lufinkey/react-native-spotify```
- ```react-native link @lufinkey/react-native-spotify```

No external in this directory:

```
$ ls node_modules/@lufinkey/react-native-spotify/ios/
HelperMacros.h             RCTSpotify.m               RCTSpotify.xcworkspace     RCTSpotifyConvert.m        SpotifyWebViewController.m
RCTSpotify.h               RCTSpotify.xcodeproj       RCTSpotifyConvert.h        SpotifyWebViewController.h
```

**Comment by lufinkey** [comment]
Ah you're right I forgot to init the submodules before I published the package

**Comment by lufinkey** [comment]
Updated the npm module, and added a prepublish script so I don't forget to init submodules next time
