### ISSUE TITLE
UIWebView is no longer accepted

### ISSUE THREAD

**Issue by ColtraneNadler** [lufinkey/react-native-spotify#171]
I can't seem to find UIWebView in the project, and where to remove/update it.
But I continue to get this error when I try to submit my app to the app store with the rn-spotify-sdk project.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Any ideas?
I tried removing the examples in the external folder of the sdk as well.

**Comment by lufinkey** [comment]
What version of the module are you on?

**Comment by ColtraneNadler** [comment]
1.2.14

The most updated from NPM. Is there another place I should be sourcing the package from for a more updated version?

**Comment by lufinkey** [comment]
That should have removed all permissions. Do you still have
SpotifyAuthentication linked in your frameworks? You should unlink that

**Comment by ColtraneNadler** [comment]
I'm just using cocoapods.

**Comment by ColtraneNadler** [comment]
RNSpotify (1.2.14)

Could the pods dependency still have it?

**Comment by lufinkey** [comment]
Yeah it does. I'll update the module tonight when I get the chance.

**Comment by ColtraneNadler** [comment]
Awesome thanks so much!

**Comment by ColtraneNadler** [comment]
Let me know once you've updated. Thanks again :)

**Comment by ejimenez93** [comment]
+1 on this. Would love to get notified once this is fixed

**Comment by ejimenez93** [comment]
@lufinkey -- any updates here? Would love to see this get fixed as we are blocked by this to send to the App Store

**Comment by Ticalie** [comment]
Workaround is found here: https://github.com/lufinkey/react-native-spotify/issues/140#issuecomment-627382000

**Comment by lufinkey** [comment]
Just updated it. Sorry. I kept meaning to and then I would just forget. It should be up now

**Comment by ColtraneNadler** [comment]
hey!

in the new update, spotify gets held up on login.
no longer progresses past login in 1.2.15.

**Comment by lufinkey** [comment]
Have you made sure to clean the project?

**Comment by ColtraneNadler** [comment]
Yes. It works fine on 1.2.14, but in version 1.2.15 when calling the Spotify.login() function- running debug on an iPhone device + production... it throws this error -

error logging in Error: Could not connect to the server.
    at promiseMethodWrapper (NativeModules.js:103)
    at Object.Spotify.login (Spotify.js:14)
    at login$ (spotify-service.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:43)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)

**Comment by lufinkey** [comment]
This sounds like an issue with your setup. The only thing I changed was removing a reference to SpotifyAuthentication.framework

**Comment by lufinkey** [comment]
It sounds like it's maybe having an issue connecting to your development server?
