### ISSUE TITLE
Could not find a declaration file for module 'rn-spotify-sdk'.

### ISSUE THREAD

**Issue by goodluckgod** [lufinkey/react-native-spotify#174]
![resim](https://user-images.githubusercontent.com/42766561/100528693-7765bb80-31f0-11eb-9b41-6d87ac9028ae.png)

I have issue with importing module, i tried on example app and it's same.

I install with tutorial and i made all things.

![resim](https://user-images.githubusercontent.com/42766561/100528706-95cbb700-31f0-11eb-9f0a-0474af0ab6ae.png)

**Comment by lufinkey** [comment]
This looks like it's possibly an issue with a lack of type files. Are you using typescript or flow or some other type checker?

**Comment by lufinkey** [comment]
Are you still having this issue?
