### ISSUE TITLE
Objective c - skipToPrevious not working.

### ISSUE THREAD

**Issue by khushbu1234** [lufinkey/react-native-spotify#176]
Thank you for contributing to `rn-spotify-sdk`!

Be sure to include your react-native version, platform you're developing for, and iOS or Android version.

Please do not open issues about getting the module to work unless you have tried using both the example app and the example token swap server. Please make sure you have tried running on the latest react-native version before submitting a bug.

**Comment by lufinkey** [comment]
Please don't open multiple duplicate issues, and please actually include a description of the issue.
