### ISSUE TITLE
Objective c - skipToPrevious not working. Not able to change Previous Song. 

### ISSUE THREAD

**Issue by khushbu1234** [lufinkey/react-native-spotify#178]
I have integrated SpotifySDK in Swift as well.in this skip(toPrevious: and skip(toNext: both Working perfect.
 but in Objective c, skipToNext Working Perfect
     
    But  skipToPrevious Not change previous song.
     [appRemote.playerAPI skipToPrevious:^(id  _Nullable result, NSError * _Nullable error) {
        if (error) {
            // Operation failed
        }
        else
        {
            // Operation succeeded
        }
    }];

**Comment by lufinkey** [comment]
You have opened this issue in the wrong place. This is not related to the spotify streaming SDK nor the react native wrapper for it. This is the remote SDK.
