### ISSUE TITLE
disallowed_useragent in google signin

### ISSUE THREAD

**Issue by denis0324** [lufinkey/react-native-spotify#182]
I am getting the below issue when I try `google signin` 

```
403. That’s an error.
Error: disallowed_useragent

Google can’t sign you in safely inside this app. You can use Google sign-in by visiting this app’s website in a browser like Safari or Chrome.
```

react native version: 0.61.5
rn-spotify-sdk version: 1.2.15
platform: iOS

**Comment by lufinkey** [comment]
Oof. May need to add a fake user-agent for this. I'm not working on this module anymore but I think that it should be something documented on WKWebView

**Comment by lufinkey** [comment]
@denis0324 I've added a `loginUserAgent` option to pass a custom user agent to the login flow. It only works on iOS right now, but it's up on the latest master if you want to test it out

**Comment by lufinkey** [comment]
@denis0324 sorry this was late, but please let me know if this solves your issue when you get this chance

**Comment by lufinkey** [comment]
Since I've gotten no response, I'm going to close this
