### ISSUE TITLE
handleAuthURLAsync needed for remote JS debugging

### ISSUE THREAD

**Issue by drewandre** [lufinkey/react-native-spotify#19]
Thanks Luis for work on this library!

This issue is an extension of #3 (closed). In order to use remote JS debugging, all functions should run asynchronously. `handleAuthURL` should have an async version like `isLoggedInAsync` and `isInitializedAsync` in order for the full authorization cycle to work.

Copied from example file:
```
App.handleOpenURL = event => {
  // below is the function (handleAuthURL) that chrome doesn't like
  if (Spotify.handleAuthURL(event.url)) {
    return true;
  }
  return false;
};
Linking.addEventListener('url', App.handleOpenURL);
```

**Comment by lufinkey** [comment]
I've added handleAuthURLAsync to the available functions
