### ISSUE TITLE
Failure to find dependent files

### ISSUE THREAD

**Issue by Acciaccatura** [lufinkey/react-native-spotify#192]
I ran into the following issue::
```
Execution failed for task ':rn-spotify-sdk:generateDebugRFile'.
> Could not resolve all files for configuration ':rn-spotify-sdk:debugCompileClasspath'.
   > Could not find :spotify-android-auth-1.0.0:.
     Required by:
         project :rn-spotify-sdk
   > Could not find :spotify-player-24-noconnect-2.20b:.
     Required by:
         project :rn-spotify-sdk
```
but I notice the files that this program is looking for is under `libs`. I added:
```
repositories {
  ...
  flatDir {
    dirs 'libs'
  }
}
```
to ask Gradle to look in that directory and it seemed to work. Would you be able to look into why I had to edit this node_module for this to work? If you find that this is necessary, could you add this to the Gradle file? Thanks.

I'm on npm 6.9.0.

**Comment by lufinkey** [comment]
Did you follow the steps under the Android section of the readme? You should already be adding the libs folder, but you should be adding it to look under `rn-spotify-sdk`

**Comment by lufinkey** [comment]
Since there hasn't been an answer, I'm going to close this issue
