### ISSUE TITLE
Not linking correctly and other issues

### ISSUE THREAD

**Issue by ufmemo** [lufinkey/react-native-spotify#2]
Thanks for sharing your project,  I'd love to use this in my project but I've had a rough time getting it working (ios). 

1) react-native link command wasn't linking for me.  I had to manually link the project.  I'm not sure why.

2) Once linked it failed to build for me w/ an error at RCTSpotifyConvert.m line 21. I'm not sure if this is an artifact from your testing/debugging. Once I commented it out the project began to compile and I could see the native module loading on the JS side.  

I continue to work my way through issues.  

It would be incredibly useful to have a simple example of a one file working example for IOS and Android.

**Comment by lufinkey** [comment]
Could you post the actual errors you were getting please?

**Comment by ufmemo** [comment]
Thanks.  If I comment this line out it builds.

![image](https://user-images.githubusercontent.com/7832954/33182898-b78d4212-d043-11e7-9c4d-a2d2087c56d4.png)

The issue I'm stuck on now is that once the Spotify Auth screen loads and I log in it doesn't redirect me back to my app.  Have read and reread the linking stuff on the react native docs, I have looked at your reference impl in your doc but no luck.  I don't see an error in the Node console or in Xcode logs.  Any thoughts?  Any help would be much appreciated.  Thanks.

**Comment by lufinkey** [comment]
I'll add an example project once I get the chance. Hopefully this weekend

**Comment by sbehrends** [comment]
I did solve how to initialized it, but I am failing in getting auth to work.
Some example or more details on it would be awesome!

I believe that the README needs to also explain to download and add spotify-sdk

**Comment by lufinkey** [comment]
If the login screen isn't disappearing, it might be that you haven't set the correct redirect URL for your Spotify application, which you can do [here](https://developer.spotify.com/my-applications/).

As for adding the spotify sdk, you don't actually need to do that. The README explains that you can link the framework from the react-native-spotify ios project folder

**Comment by lufinkey** [comment]
I added an example project. You just need to change the spotify options in InitialScreen.js and the URL scheme in the iOS info.plist file. I'll add this to the README when I get the chance.

**Comment by lufinkey** [comment]
Could you please verify if this fixed the issue?

**Comment by ufmemo** [comment]
Thank you, Luis.  I was able to get it working.  

Can I make a recommendation? Is it possible to change all function to be asynchronous?   When using the chrome debugger the application doesn't run if any of the calls to native functions are synchronous (i.e. isInitialized, isLoggedIn, getPlaybackState).

![image](https://user-images.githubusercontent.com/7832954/33393092-00572ae0-d50c-11e7-8b7c-6d8148919711.png)

**Comment by lufinkey** [comment]
I can add some alternative methods to the synchronous ones, but I'd like to keep the synchronous methods in there because all they do is return a boolean, so it doesn't make a lot of sense to force you to use a callback for something like that.

**Comment by lufinkey** [comment]
Do you mind making a separate issue for the synchronous methods thing?
