### ISSUE TITLE
Authentication Service Unknown Error 

### ISSUE THREAD

**Issue by juangarcia-ts** [lufinkey/react-native-spotify#20]
Hello,

First of all, thank you for the amazing job so far!

I wasn't having any issues using your project in my app until I generated a signed release APK.

After that, every time I call the login method, this error appears:

![error](https://user-images.githubusercontent.com/20177101/34902842-64e45a92-f80b-11e7-8894-d8599db6e121.jpg)

Thanks!

**Comment by lufinkey** [comment]
The only thing I've been able to find on this error is this [stackoverflow thread with no answers](https://stackoverflow.com/questions/46710854/spotify-android-sdk-authentication-service-unknown)

Have you registered your package SHA1 fingerprint on the Spotify developer backend?

**Comment by juangarcia-ts** [comment]
Yeah, it worked.

Sorry, I completely forgot about it.  👎 

Thanks for your time!
