### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by juangarcia-ts** [lufinkey/react-native-spotify#21]
Hello again,

Is there any way to make optional or able to customize the dialogs from commit `0ae99a6`?

I'd like to keep my app as clean as possible.

Thank you so much.

**Comment by lufinkey** [comment]
I can honestly just remove them. It doesn't really do anything except bridge the 2 Activities

**Comment by juangarcia-ts** [comment]
If nobody disagrees, I think it would be great. Thank you!

**Comment by lufinkey** [comment]
Actually there is a dialog needed there, since the app is performing additional login logic. I could just change the text to "Logging in" and/or have a `strings` option in the initialize method

**Comment by juangarcia-ts** [comment]
The dialog after login I agree that's necessary but the ones from commit `0ae99a6` don't add anything to UX imo.

**Comment by lufinkey** [comment]
Those are the ones I mean. The problem is that it needs to perform token swap and initialize the Player object, but while that's happening, if there's nothing on screen blocking user input, the user could hypothetically hit the login button again, and there should only be a single login process occurring at any given time, to prevent race conditions.

**Comment by juangarcia-ts** [comment]
Sorry for my misunderstood.

Anyway, I prefer to deal with this problem by myself. For example, I disable my button as soon as the user hit the button.

But I totally understand if you prefer to keep the dialogs.

It'd still be great if you just implement the `strings` option. Maybe hide them when it's `null` or `undefined`.

**Comment by lufinkey** [comment]
I've updated the dialog after login to be consistent with the default loading dialogs. You can check it out in the dev branch. Does this work better for you?

![screenshot from 2018-01-16 17-26-54](https://user-images.githubusercontent.com/7820113/35015568-ea0de416-fae2-11e7-96b6-513cbf6401f8.png)

**Comment by juangarcia-ts** [comment]
I've just tested here and it's a lot better! Thank you!

And I really know that wasn't a priority, so thank you again for being so helpful

**Comment by juangarcia-ts** [comment]
Hey @lufinkey,

I just noticed something:

After user logins, the dialog shows up in the center of the screen and in user's default language. However, the new one appears in the top of the screen and only in english.

Here are some pics:

[Old dialog (PT-BR)]
![photo_2018-01-17_01-49-21](https://user-images.githubusercontent.com/20177101/35024845-ec24c0d0-fb28-11e7-9bd0-ae6e92f9ad3c.jpg)

[New one]
![photo_2018-01-17_01-54-19](https://user-images.githubusercontent.com/20177101/35024920-581c99fc-fb29-11e7-8139-e880f9f7ea56.jpg)

**Comment by lufinkey** [comment]
Unfortunately, I can't duplicate the anchoring to the top of the screen, but I've made a commit to the dev branch that may fix it.

As for the translating, I definitely don't know how to get the actual default system "Loading..." text, but I'll add a `strings` option

**Comment by lufinkey** [comment]
You can now change the "Loading..." string in the initialize options by setting `android`.`loginLoadingText`

**Comment by juangarcia-ts** [comment]
It's great now. Thank you so much :grin:
