### ISSUE TITLE
Update README to explain OAuth server and how to use it

### ISSUE THREAD

**Issue by yamalight** [lufinkey/react-native-spotify#22]
I'm trying to setup a simple server to have refreshable tokens. I've setup my own server and configured it as required, executing requests manually produces correct tokens.
I've configured react-native-spotify the following way:
```js
const spotifyOptions = {
  clientID: 'my-id',
  sessionUserDefaultsKey: 'SpotifySession',
  redirectURL: 'myapp://auth',
  tokenSwapURL: 'https://my.url/swap',
  tokenRefreshURL: 'https://my.url/refresh',
  scopes: ['user-read-private', 'playlist-read', 'playlist-read-private', 'streaming'],
};
Spotify.initialize(spotifyOptions, (loggedIn, error) => {
  // ...
});
```
But all I currently get is an error "Missing expected response parameters" with following app crash.
What's stranger - the server doesn't get any incoming requests at all.
Any idea why that might happen? Am I missing something in my config?

**Comment by lufinkey** [comment]
Are you checking the POST variables or the GET variables? The token swap parameters are sent via POST as application/x-www-form-urlencoded

**Comment by lufinkey** [comment]
It also says "Missing expected response parameters", which means the server isn't sending back the data that it should be. See [this](https://developer.spotify.com/technologies/spotify-ios-sdk/token-swap-refresh/) for an example of the request and response format

**Comment by yamalight** [comment]
@lufinkey ahh, adding `application/x-www-form-urlencoded` body parser fixed the issue, thanks!
would be great to have that mentioned somewhere in the docs IMO 🤔 

going to close the issue now, thanks!

**Comment by robertoost** [comment]
Good idea to include this in the docs, indeed.

**Comment by juangarcia-ts** [comment]
Is it really necessary to setup a server for this task?

Couldn't this be done by implementing a `refreshTokens` method that'd just send a request to the `api/token` endpoint and change them in Auth class?

**Comment by lufinkey** [comment]
The OAuth standard requires you to store your client secret on a server, so
you cannot swap your token directly from the device because it requires the
client secret

**Comment by yamalight** [comment]
@lufinkey I could send a PR with docs for this issue if you are OK with this 😄

**Comment by lufinkey** [comment]
Go for it

**Comment by lufinkey** [comment]
Also, please ensure that you're working on the dev branch

**Comment by yamalight** [comment]
@lufinkey PR sent!

**Comment by yamalight** [comment]
@lufinkey will prepare and send a new PR with encryption and readme for server as discussed in a few mins.

**Comment by yamalight** [comment]
@lufinkey PR sent! I think I've addressed everything 🤔

**Comment by chrismpalmer** [comment]
Friends, I don't mean to use this as a support medium but I did have a question. Other than setting the token swap url and the token refresh url is this all that is needed? I assume the Spotify IOS SDK handles the rest? I couldn't  really see any support for it in the library's code. But I also don't see it calling my end points. @yamalight seems like he is getting calls....I left it running in suspend on my phone and didn't get any calls.

**Comment by lufinkey** [comment]
The library doesn't handle the token swap/refresh server and you have to make it yourself and give the URLs to the library. If you don't use a token swap/refresh server and leave the options out, then you'll only be able to stay logged in for an hour

**Comment by chrismpalmer** [comment]
@lufinkey Thank you I understand. I did this...but don't see any calls. I have an endpoint I built. The related question is does the library also handle restarts? Thanks again I really appreciate this library it helped us do something really quick.

**Comment by lufinkey** [comment]
what do you mean restarts? And what do you mean you don't see any calls? Do you mean the server isn't receiving your request, or the server isn't sending a response, or what? I need you to be more specific

**Comment by lufinkey** [comment]
If sessionUserDefaultsKey isn't specified, the app will not save your login status on restart

**Comment by chrismpalmer** [comment]
@lufinkey thanks, ok.... I built the endpoints , I have them exposed publicly ,

I config the library like 

`                var spotifyOptions = {
                    "clientID":Config.SPOTIFY_CLIENT_ID,
                    "sessionUserDefaultsKey":"SpotifySession",
                    "redirectURL":Config.SPOTIFY_REDIRECT_URL,
                    "scopes":["user-read-private", "playlist-read", "playlist-read-private", "streaming"],
                    "tokenSwapUrl":Config.SPOTIFY_TOKEN_SWAP_URL,
                    "tokenRefreshUrl":Config.SPOTIFY_TOKEN_REFRESH_URL,
                };
                Spotify.initialize(spotifyOptions, (loggedIn, error) => {
`
My URLS are 
`SPOTIFY_TOKEN_SWAP_URL=https://bewell-dev-rest.ngrok.io/public/spotify/tokenswap
SPOTIFY_TOKEN_REFRESH_URL=https://bewell-dev-rest.ngrok.io/public/spotify/tokenrefresh
`

I don't see any calls to the web services specified. If I kill the app I have to login again. Is this more clear?

**Comment by lufinkey** [comment]
It may be that your URL isn't correct, as others have been able to get the app to call their endpoint when they log in. Have you tried using the example app?

As for login not persisting, I'm not sure why this is happening. Does the login persist if you don't specify tokenSwapURL and tokenRefreshURL? Also, are you calling Spotify.initialize on every app start?

**Comment by lufinkey** [comment]
Also, have you tried hitting your server endpoints manually with a tool like [Postman](https://www.getpostman.com/) to see if that works?

**Comment by chrismpalmer** [comment]
I will try with the same endpoint in the example app.

I will also test clearing the URLS to see if session persists.

I don't call Spotify initialize on start, but I do every time I need it the first time. Yes I can call the endpoints. Thanks for helping.

**Comment by lufinkey** [comment]
Alright, let me know if you end up fixing the issue, and what ends up fixing it, because it might be helpful for others.

**Comment by chrismpalmer** [comment]
Empty URLS , session does not persist.
Endpoints can be called manually.

**Comment by lufinkey** [comment]
So what happens when you try to log in? Does it return an error? Also, are you running this on Android or iOS?

**Comment by chrismpalmer** [comment]
Standby... I just saw a call come in with the sample app , "I think "
GET  /public/spotify/tokenswap

**Comment by lufinkey** [comment]
It should be a post request

**Comment by chrismpalmer** [comment]
**Example App**
Ok, the example app saves the session... Starting the app does not call the endpoints.
But I was using the KEY tokenSwapUrl instead of tokenSwapURL as well as the other. I have this configured in example app. Are you saying the URL should be hit on app start?

**Comment by lufinkey** [comment]
The URL is only hit on app start if the old session has expired. Otherwise,
it just resumes the old session

**Comment by chrismpalmer** [comment]
ok, I will let that run a bit... I guess my React-native version is causing an issue. There were some errors using the library with the synchronous methods.

**Comment by lufinkey** [comment]
Yeah the chrome debugger doesn't let you use synchronous methods

**Comment by chrismpalmer** [comment]
I am all good the react-native version for storing the settings and URL in the key refresh and swap URL. I had Url...not URL thanks for the great library.
