### ISSUE TITLE
> Error: more than one library with package name 'com.lufinkey.react.spotify'

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#28]
In the instructions on how to install ``react-native-spotify`` through npm, you mention having to replace "``@lufinkey/react-native-spotify``" with "``@lufinkey_react-native-spotify``" in several .gradle files. This works during initial setup, but after linking the project again, and running npm i, my project broke down.
```
> Error: more than one library with package name 'com.lufinkey.react.spotify'
```
It seems the replaced versions of the string have been raised from the dead to haunt me, as both versions of the string are now present in my .gradle files.

```
    compile project(':@lufinkey/react-native-spotify')
    compile project(':@lufinkey_react-native-spotify')
```
```
include ':@lufinkey/react-native-spotify'
project(':@lufinkey/react-native-spotify').projectDir = new File(rootProject.projectDir, '../node_modules/@lufinkey/react-native-spotify/android')
include ':@lufinkey_react-native-spotify'
project(':@lufinkey_react-native-spotify').projectDir = new File(rootProject.projectDir, '../node_modules/@lufinkey/react-native-spotify/android')
```
Removing the lines that use a "/" does allow the project to start on android, but it fails immediately ( as shown in the image below ).
I have the feeling that this has something to do with this double module issue. Any thoughts on how to fix this?

<details>
 <summary>See Image here</summary>

![image](https://user-images.githubusercontent.com/33265853/35160228-da7f954c-fd3c-11e7-9495-a0550c3baee9.png)

</details>

**Comment by lufinkey** [comment]
Yeah, as mentioned in the README, this is a bug with `react-native link`. It's been [brought](https://github.com/facebook/react-native/issues/17029) [up](https://github.com/facebook/react-native/pull/17000) [multiple times](https://github.com/facebook/react-native/pull/17094) in issues, but somehow it still isn't fixed, despite multiple people suggesting the very obvious solution of substituting the `/` with a `_`. I don't know when it'll be fixed, but this is just something we'll have to deal with until then, since I have to use a scoped package due to all the squatters on npm hosting half finished packages. 😒

**Comment by robertoost** [comment]
I managed to find all duplicate entries. The fix for a double link is as follows:
remove the wrong lines from:
```
android/settings.gradle
android/app/build.gradle
android/app/src/main/java/.../MainApplication.java
```
Perhaps it'd be good to mention this fix for a double link in the instructions of your package install on npm?

**Comment by lufinkey** [comment]
So do you think I should make an install script that echoes information
about it, or just add it to the README?

**Comment by robertoost** [comment]
I'd say add it to the bottom of readme on npm, and an installscript would be good aswell.

**Comment by robertoost** [comment]
Perhaps a better solution for now would be to release the package under a different name. The current version breaks the project every time someone executes react-native-link. It's a minor annoyance for me, but the members of our team that are working on entirely different sections of the app are not having a good developer experience, to say the least.

**Comment by lufinkey** [comment]
I'd say use the GitHub package instead of the npm one. That's why I've maintained the master branch and the npm branch

**Comment by lufinkey** [comment]
If I were to release the package under a different name, do you have any recommendations?

**Comment by adebree** [comment]
How about: react-native-spotifysdk?

**Comment by lufinkey** [comment]
I tried that one. It collides with [react-native-spotify-sdk](https://www.npmjs.com/package/react-native-spotify-sdk) because it's too similar

**Comment by adebree** [comment]
Oh, that's annoying! How about: rn-spotify-sdk It's the same prefix as for example rn-splash-screen

**Comment by adebree** [comment]
@lufinkey are you happy with the above suggestion? It would make use really happy if you could get the library published without the scoped prefix so we can workaround the react-native / gradle issue. Thanks!

**Comment by lufinkey** [comment]
Yeah I'll try to deprecate the previous name and switch over on the next update

**Comment by Titozzz** [comment]
I'll probably work on fixing react native link soon, just to let you know, because scoped packages are the new norm, and should not have to rename

**Comment by Titozzz** [comment]
https://github.com/facebook/react-native/pull/18275

**Comment by robertoost** [comment]
Looks like the pull-request fixing this issue in react-native got approved! Will we be able to close this issue soon?

**Comment by lufinkey** [comment]
I'm still going to convert it away from a scoped package anyway, so I'm going to leave this open so that I remember to do that on the next release

**Comment by lufinkey** [comment]
the package has been rescoped as `rn-spotify-sdk` and pushed to npm
