### ISSUE TITLE
Change README to use Linked Frameworks instead of Embedded Binaries

### ISSUE THREAD

**Issue by adebree** [lufinkey/react-native-spotify#29]
Ran in an unfortunate problem while exporting an app with @lufinkey/react-native-spotify installed.

Shortest steps to reproduce:

- Create an empty / new react-native project ```react-native init spotifytest```
- ```cd spotifytest```
- Go through the installation steps of @lufinkey/react-native-spotify: 
- ```npm install --save @lufinkey/react-native-spotify```
- ```react-native link @lufinkey/react-native-spotify```
- Manually add the Frameworks from ```node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK``` to Embedded Binaries in your project settings. 
- Then add ```../node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK``` to Framework Search Paths in your project settings.
- Select in XCode a development team and make sure the app is signable
- Select XCode menu Product => Archive
- After successful build / archive go in XCode menu to Window => Organizer
- Select in the dialog the Archive that just has been made and press the 'Export' button:
![image](https://user-images.githubusercontent.com/478872/35340313-1199fcae-0123-11e8-8ecb-476179fc97aa.png)
- Select 'App Store' option as method of Distribution and press next:
![image](https://user-images.githubusercontent.com/478872/35340351-2c360594-0123-11e8-99b8-ee8cfa415356.png)

We are encountering this issue on both local XCode and Bitrise while making exports. This error is not given when exporting before installing the @lufinkey/react-native-spotify package. I am still investigating if there is more information available.

**Comment by lufinkey** [comment]
Very weird. Does it happen when you don't have the Spotify module installed?

**Comment by adebree** [comment]
No, it doesn't happen when I don't install the Spotify module. 

It seems to be related by the instruction:

```Manually add the Frameworks from node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK to Embedded Binaries in your project settings.```

I have interpret that as "go to finder, and drag the 3 framework files from the node_modules folder on top of XCode on the section 'Embedded Binaries'". But when I remove the 3 Frameworks from the list of Embedded Binaries and only have them present in the list of 'Linked Frameworks and Libraries' it results in a functional export. The Frameworks did show up in that list after dragging the Frameworks on the 'Embedded Binaries'.

**Comment by lufinkey** [comment]
It may be that they just need to be linked, and not embedded. If that's the case I'll update the README. [Here's Spotify's instructions for setting up the frameworks](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions)

**Comment by adebree** [comment]
I think it should be just linked. The documentation of the iOS Spotify SDK is not clear about it, but when inspecting their demo app it shows the libraries linked:

[Simple Track Playback demo app of ios-sdk](https://github.com/spotify/ios-sdk/tree/master/Demo%20Projects/Simple%20Track%20Playback)

![image](https://user-images.githubusercontent.com/478872/35378072-be1e7c28-01b1-11e8-9fa0-ad86bbd84c0e.png)
