### ISSUE TITLE
Calling synchronous methods on native module is not supported in Chrome

### ISSUE THREAD

**Issue by ufmemo** [lufinkey/react-native-spotify#3]
The chrome debugger complains if you make synchronous native calls.  Please add asynchronous alternatives.  

![image](https://user-images.githubusercontent.com/7832954/33407587-063a5b38-d540-11e7-9fc3-9b9dbc02144d.png)

**Comment by lufinkey** [comment]
Async method alternatives have been added to the documentation

**Comment by KongfuMan** [comment]
Same issue.!  I followed the track, and found that   `getConstantsForViewManager` is sync, which caused the error. Anyone know how to fix it ?

**Comment by lufinkey** [comment]
I don't think that method is from this module
