### ISSUE TITLE
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

### ISSUE THREAD

**Issue by Juliocbr** [lufinkey/react-native-spotify#30]
Hi,

The problem occurs when I enable debug mode with chrome, this error appears:

_Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

 Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.

This error is located at:
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)_

When I stop the debug mode the error disappears.
I'm doing the library test with the ios emulator

Thanks.

**Comment by lufinkey** [comment]
This is not an error. If you had googled the problem, you'd see that the chrome debugger simply doesn't support synchronous methods. If you check the README, there are alternative methods provided for every synchronous method.. They are the ones with "Async" after the name. I'm not sure how exposing constants would change anything?

The stack trace you gave me tells me absolutely nothing about the problem, as none of those files are in this module.

**Comment by Juliocbr** [comment]
Hi, you're right, using Async methods solved my problem. Thanks
