### ISSUE TITLE
getAuthAsync is not a function, also getAuth is not a function

### ISSUE THREAD

**Issue by Juliocbr** [lufinkey/react-native-spotify#31]
Hi,

I need the accessToken from login with spotify, but when I use getAuthAsync or getAuth this error appears: 

_reactNativeSpotify2.default.getAuthAsync is not a function

_reactNativeSpotify2.default.getAuth is not a function

I checked RCTSpotify.h y RCTSpotify.m from ios folder and these methods not appears.

Thanks.

**Comment by lufinkey** [comment]
Just added the missing functions. I guess I forgot to add the iOS methods. Thanks for letting me know.
