### ISSUE TITLE
country arg for 'getArtistTopTracks()' weird error on IOS

### ISSUE THREAD

**Issue by PaulySim** [lufinkey/react-native-spotify#32]
This piece of code works perfectly fine on Android, but throws an error on IOS:
```
Spotify.getArtistTopTracks(
      "<artist-id>",
      { country: "GB" },
      {},
      (result, error) => ...
```

Error:
```
JSON value '{
    country = GB;
}' of type NSMutableDictionary cannot be converted to NSString
```

**Comment by chrismpalmer** [comment]
I am getting an error like this as well. 

```javascript
    Spotify.getArtistTopTracks(spotifyId,'US',null, (popular, error) => {
```
Is my source call per the documentation? 
![screen shot 2018-01-26 at 12 06 46 am](https://user-images.githubusercontent.com/7710236/35430376-d64a2470-022c-11e8-958c-5740849bb451.png)

**Comment by lufinkey** [comment]
The second argument should just be a string, the third argument can be null or an object with optional parameters (currently there aren't any other optional parameters for this method though), and the fourth argument is a callback. I've fixed the incorrect parameters on Android, so it should work as expected now.

**Comment by lufinkey** [comment]
What are you changing in the objective-c code to make it work? Are you just passing options directly?

**Comment by chrismpalmer** [comment]
params:options <= Current

Changed:
params:body <= Seems to do the trick.

**Comment by lufinkey** [comment]
Wow yeah you're right. Looks like I forgot to change that parameter. Just updated it in npm, so try it now
