### ISSUE TITLE
Issue with getAuth and getAuthAsync

### ISSUE THREAD

**Issue by Juliocbr** [lufinkey/react-native-spotify#33]
Hi, 

Thanks for updating the library but when I use getAuth or getAuthAsync this error appears:

Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' was thrown while invoking getAuthAsync on target Spotify with params (
    199
)

callstack: (
	0   CoreFoundation                      0x000000010525012b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001036fdf41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001052900cc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000105164951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001051647db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   spotifyAPI                          0x0000000102b226b7 +[RCTSpotifyConvert SPTAuth:] + 487
	6   spotifyAPI                          0x0000000102b28078 -[RCTSpotify getAuth] + 56
	7   spotifyAPI                          0x0000000102b2810a -[RCTSpotify getAuthAsync:] + 106
	8   CoreFoundation                      0x00000001051d436c __invoking___ + 140
	9   CoreFoundation                      0x00000001051d4240 -[NSInvocation invoke] + 320
	10  CoreFoundation                      0x00000001051ecc26 -[NSInvocation invokeWithTarget:] + 54
	11  spotifyAPI                          0x00000001028e794c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796
	12  spotifyAPI                          0x00000001029972e2 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786
	13  spotifyAPI                          0x0000000102996e0f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
	14  spotifyAPI                          0x0000000102996d89 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	15  libdispatch.dylib                   0x0000000109af7177 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000109af81ba _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000109affd3d _dispatch_queue_serial_drain + 654
	18  libdispatch.dylib                   0x0000000109b005a0 _dispatch_queue_invoke + 329
	19  libdispatch.dylib                   0x0000000109afcc97 _dispatch_queue_override_invoke + 477
	20  libdispatch.dylib                   0x0000000109b02980 _dispatch_root_queue_drain + 568
	21  libdispatch.dylib                   0x0000000109b026ea _dispatch_worker_thread3 + 119
	22  libsystem_pthread.dylib             0x0000000109fb75a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x0000000109fb707d start_wqthread + 13
)

I use ios emulator.

Thanks.

**Comment by lufinkey** [comment]
Just fixed this bug in iOS. Update your module and you should get the change.

**Comment by Juliocbr** [comment]
Thank you very much for updating the library, I was able to obtain the user's token with the methods.
