### ISSUE TITLE
queueURI is not working correctly

### ISSUE THREAD

**Issue by justin-segler** [lufinkey/react-native-spotify#36]
I have no clue how this works. I can play an individual track but I have no clue how to play through a playlist. Is there a function to just play through the queued songs in the playlist? i experimented with setPlaying but that does not play through the playlist. Thanks

**Comment by lufinkey** [comment]
You should only have to use playURI. You just need to be sure to give it a playlist URI instead of a track URI

**Comment by justin-segler** [comment]
Where do I get that uri?

**Comment by lufinkey** [comment]
From the search method, or any of the other random endpoints that provide
Uris

**Comment by justin-segler** [comment]
Oh, I am referring to creating a queue of your own. I'm looking to create a queue of at least 10 songs but I notice that queueURI does not always work. I want to simply search for songs and then add songs to a queue of indefinite length to be iterated through. Does your library support this?

**Comment by lufinkey** [comment]
If queueURI sometimes doesn't work, then that's probably a bug. Can you provide an example of when it works and when it doesn't work?

queueURI is the only available method in the Spotify SDK for queueing songs.

**Comment by justin-segler** [comment]
Well, what my code is currently doing is searching Spotify for a few songs, grabbing the uri's of those songs, and then for each song calling queueURI with the corresponding URI. However, I am confused as to how to play the queue. When I call playURI and pass in the first URI in my queue and I retrieve the queue information, all that is stored is the currentTrack. The nextTrack field is empty

**Comment by justin-segler** [comment]
Just ran another test. There seems to be something wrong with the playbackMetadata data structure. When I play the first in my queue and print out the metadata using playbackMetadataAsync, all fields are null. When I skip to next and play the next in queue, the current song is correctly updated to the next in the queue, but the previous song field in playbackMetadata is null... Perhaps a bug?

**Comment by justin-segler** [comment]
And this causes issues when calling skipToNext and skipToPrevious. Because the previousTrack and nextTrack fields in playbackMetadata are null, these functions do not actually perform as supposed, that being to skip either forward or backward and play the previous or next song in the queue as expected.

**Comment by lufinkey** [comment]
I believe you can only call queueURI after playback has started, so you'll need to already have started playing with playURI when you call queueURI

**Comment by lufinkey** [comment]
If it's a bug, it's likely a bug with the spotify SDK, because I'm directly returning those values and calling those methods from the Spotify SDK objects. Are you doing this on iOS or Android?

**Comment by justin-segler** [comment]
I'm doing it directly through React Native. Currently testing on iOS though

**Comment by lufinkey** [comment]
If you want to do some digging in the iOS native code and submit a pull request, that would be much appreciated. I probably won't have time to look into this for a while

**Comment by justin-segler** [comment]
Okay. Calling queueURI after playURI helped with the playbackMetadata state. Do you happen to know if you can queue more than one song to this queue? Currently, all that the data structure is storing is the next song rather than a list of next songs.

**Comment by lufinkey** [comment]
Yeah that's literally all that spotify gives you. The native SDK doesn't even give you a list of songs in the queue. If you want to maintain a list like that, you'll have to maintain it in your own code. You can queue multiple songs though, there's just no way to get a list of them.

**Comment by lufinkey** [comment]
I'm currently in the process of adding events to the module, so once that's finished, it'll be easier to maintain a list like that.

**Comment by justin-segler** [comment]
Hmm. So it can maintain a list of more than one queued song but it just shows you the next song, previous song, and current song in the queue? 

And makes sense. When are you planning on adding those events?

**Comment by lufinkey** [comment]
When I've reached a stopping point on another project that I'm currently working on. I'll probably have some time in between classes this week, though.

**Comment by justin-segler** [comment]
Great. If you don't mind me asking, what events are you adding?

**Comment by justin-segler** [comment]
Hmm okay. That could possibly be a bug either with your library or with the SDK. Any ideas as to which it is?

**Comment by lufinkey** [comment]
No idea. Have you checked the error object to see if anything gets returned?

**Comment by justin-segler** [comment]
Yeah. Error is null - no error...

**Comment by justin-segler** [comment]
Also, another error I am noticing is even when I manage to correctly queue a song to be played next and it is reflected in the playbackMetadata nextTrack variable, when the current song finishes playing, the next song in the queue should automatically be playing, which it's not. Is that something that you have implemented yet, in which case there might be a bug there, or is that an error in the spotify SDK side of things?

**Comment by lufinkey** [comment]
That should definitely already be handled by the native SDK. queueURI doesn't get an error either?

**Comment by justin-segler** [comment]
Justin Segler

**Comment by justin-segler** [comment]
Yeah unfortunately no error.

**Comment by justin-segler** [comment]
If you have a chance, could you write some test code to see if you get the same problems?

**Comment by lufinkey** [comment]
I will do it when I get the chance

**Comment by justin-segler** [comment]
Were you able to test and see if the queuing and fast forwarding problems were related to your code or related to the Spotify SDK?

**Comment by sagark1510** [comment]
@lufinkey I have tried feature/events branch with RN-v0.50.4, but as soon I run the build I got error with Native modules does not conform to RNEventConformer. 
![simulator screen shot - iphone x - 2018-02-06 at 09 58 11](https://user-images.githubusercontent.com/2134076/35841835-48278e5c-0b24-11e8-8bd4-b7c8b8857b5e.png)

**Comment by lufinkey** [comment]
I'm deleting that as it's irrelevant to this issue. I am actively working on that branch so you shouldn't expect things to just work. That's why it's in a separate branch.

**Comment by lufinkey** [comment]
After investigating this issue some, I've found that queueURI is basically just broken. [This issue](https://github.com/spotify/ios-sdk/issues/717) on the iOS spotify SDK's github shows a lot of people having issues.

**Comment by sagark1510** [comment]
@lufinkey okay. I'll wait for feature/events to be stable and investigate if I can find the issue, I am not good at obj-c though. Thanks.

**Comment by lufinkey** [comment]
@sagark1510 all I'm asking is that you keep your issues related to it in [this thread](https://github.com/lufinkey/react-native-spotify/issues/15)

**Comment by lufinkey** [comment]
Okay after some more testing, I've found that if I wait long enough after calling `playURI`, then `queueURI` works, but otherwise, it does not.

In this example code from the feature/events, I waited for 3 metadataChange events before attempting to call `queueURI`, and that seemed to work:

```javascript
Spotify.playURI("spotify:track:6j67aNAPeQ31uw4qw4rpLa", 0, 0, (error) => {
	console.log("playURI finished");
	if(error)
	{
		Alert.alert("error", error.message);
	}
	Spotify.once("metadataChange", (event) => {
		Spotify.once("metadataChange", (event) => {
			Spotify.once("metadataChange", (event) => {
				console.log("metadataChange finished");
				Spotify.queueURI("spotify:track:58IwT0LhymX1XJWouVCQCg", (error) => {
					console.log("queueURI finished");
					if(error)
					{
						Alert.alert("error", error.message);
					}
				});
			});
		});
	});
});
```

This would definitely be consistent with the issues discussed on [Spotify's official iOS SDK github repo](https://github.com/spotify/ios-sdk/issues/717), so I'm going to chalk this up to an issue with the native SDK, and just add a note next to the function in the README

**Comment by justin-segler** [comment]
Great. Glad you were able to diagnose the problem! That helps me a lot actually. I will get in contact with a rep from Spotify to see how quickly they are attempting to push out a patch for this error. Glad to hear it’s not an issue with your library!

Justin Segler

**Comment by justin-segler** [comment]
Any recommendations on a short term fix? How are you creating metadataChange events?

Justin Segler

**Comment by lufinkey** [comment]
The metadataChange events are being generated from the Spotify SDK's internet events. I'm just forwarding them to javascript. The events aren't available in the npm module yet, though. I was just using them for testing here so I wouldn't have to mock up a test Objective-C project.

Also, I hate to burst your bubble, but it is really unlikely that Spotify is going to fix this, seeing as the issue has been around for multiple years. I'd recommend just making a secret playlist and populating a queue using that, since the only queue related function that Spotify provides appears to be very broken and inconsistent

**Comment by lufinkey** [comment]
I've added a note to the README about this. I might just end up excluding the function in a future release, though.

**Comment by justin-segler** [comment]
How would you go about managing a secret playlist? I understand how I would implement next and previous functions; however, how would I make the next song in the queue play after the current song finishes? This is the main functionality that I was looking for in queueURI

**Comment by lufinkey** [comment]
To start a queue, ideally, you would add create a new playlist using [this](https://developer.spotify.com/web-api/create-playlist/) endpoint, add a song to it with [this](https://developer.spotify.com/web-api/add-tracks-to-playlist/) endpoint, and then start playing the playlist's URI. Whenever you need to add more songs to a "queue", just add it to this playlist.

**Comment by justin-segler** [comment]
Dang. Not ideal but I suppose it will do. Is there a way that I can access those endpoints via my react native code? Would I simply just make a POST call to those endpoints in native JS?

**Comment by lufinkey** [comment]
The **sendRequest** function allows you to send a general request to the Spotify Web API

**Comment by justin-segler** [comment]
Brilliant. Thanks so much
