### ISSUE TITLE
 Get the authorization code through the Authorization Code Flow

### ISSUE THREAD

**Issue by Juliocbr** [lufinkey/react-native-spotify#37]
Hi,

I was wondering if there is any way to get the authorization code through the Authorization Code Flow or can only get the user access token (Implicit Grant Flow) using the library?

Thanks.

**Comment by lufinkey** [comment]
There's no reason you should need to access the authorization code. It's only used once to get the access and refresh tokens. What are you trying to use it for?

**Comment by Juliocbr** [comment]
I send this Authorization Code to backend application, the backend application use this authorization code to exchange it with an access token by making a POST request to the Spotify Accounts service (POST https://accounts.spotify.com/api/token), Spotify API responses with an access_token and refresh_token (refresh token can be used to get a new access_token), this ensures that you always have a valid token even when the user only logged in once.

**Comment by lufinkey** [comment]
Please [read the README](https://github.com/lufinkey/react-native-spotify#token-swap-and-refresh). You can set up your own server which receives the code and swaps it, or receives the refresh token and fetches another access token.
