### ISSUE TITLE
Module does not exist in the module map

### ISSUE THREAD

**Issue by justin-segler** [lufinkey/react-native-spotify#39]
I just updated my modules and now it says that it cannot find 'react-native-spotify'. I've run all of the suggested commands for clearing cache and all but nothing seems to have worked. Is this happening to just me?

**Comment by lufinkey** [comment]
Are you using the npm scoped package, or are you using the GitHub repo. Also, does react-native-spotify show up in your node_modules folder?

**Comment by justin-segler** [comment]
I am using the npm scoped package and yes, react-native-spotify is in my node_modules folder. That’s the confusing part...

**Comment by lufinkey** [comment]
Is it in the folder as node_modules/@lufinkey/react-native-spotify, or is it just node_modules/react-native-spotify? Also, have you tried deleting your node_modules folder and re-running `npm install`? And is it Xcode throwing the error, or are you getting the red screen when the app starts?

**Comment by justin-segler** [comment]
It’s in the node_modules folder but in the project is just being referenced as ‘react-native-spotify’, which I hadn’t had any problems with until something very recently, not sure what. I tried removing node_modules and rerunning npm install with no results. Also, yes the app starts up with a red screen which prevents the app from even opening. How do I check for an Xcode error? Currently just running the simulator with ‘react-native run-ios'

**Comment by lufinkey** [comment]
Have you already linked the project with `react-native link`?

Also, inside the "ios" folder of your app, there should be an xcode project. If you open that, you can just run the project from there. It's less conveniant that `react-native run-ios`, but lets you see more information

**Comment by lufinkey** [comment]
Also, if you're using the scoped package, you have to use `import Spotify from '@lufinkey/react-native-spotify'` rather than just `import Spotify from 'react-native-spotify'`

**Comment by justin-segler** [comment]
Just ran it from Xcode. No errors upon compiling and running but still shown the red screen...

**Comment by justin-segler** [comment]
Also, I’m running ESLint and it recognizes ‘react-native-spotify’ and not ‘@lufinkey/react-native-spotify'

**Comment by lufinkey** [comment]
Regardless of if you're using ESLint, the correct way to import it is by using `@lufinkey/react-native-spotify`. I'll be deprecating the scoped package soon in favor of a different module name, but for now, you have to reference it like that.

**Comment by justin-segler** [comment]
Really? Because I was able to get it working with just ‘react-native-spotify’. Should it have not referenced correctly the way that I did it?

**Comment by lufinkey** [comment]
Yes you should not have. I honestly have no idea why it would have worked before, unless you installed the module from github instead of npm. If you install the module from github, it uses the `react-native-spotify` name instead of `@lufinkey/react-native-spotify`

**Comment by justin-segler** [comment]
Fixed it. It was an issue with npm. It wasn’t clearing my npm cache, but after finicking with some settings and commands I got it to clear and now it’s fine again. Thanks

**Comment by lufinkey** [comment]
Do you mind posting your process in case somebody else has this issue?

**Comment by justin-segler** [comment]
Sure. I started by running react-native on a new port by running: ‘react-native start —port=8888’. Then I ran an ‘npm install’ and then a ‘npm cache clean —force’. Then I ran ‘sudo npm install -g npm’ and then ‘npm install’ again. I ran ‘react-native run-ios’ again and the issue was fixed. Not sure what exactly fixed it but this is what I did
