### ISSUE TITLE
Spotify SDK 'loginWithAccessToken' method

### ISSUE THREAD

**Issue by daegloe** [lufinkey/react-native-spotify#41]
Hi, thanks for a fantastic library!

Our users have already authorized via the web and therefore our server is able to generate valid access tokens without additional user interaction.

Would it be possible to skip the user auth/login process and initialize Spotify SDK playback with a valid access token provided by our server?

I noticed that the Spotify SDK `SPTAudioStreamingController` class exports a `loginWithAccessToken` method which may do just that: https://spotify.github.io/ios-sdk/Classes/SPTAudioStreamingController.html#//api/name/loginWithAccessToken:

Is this something that can be enabled/exposed in your library?

**Comment by michaelmerrill** [comment]
Really interested in this as well. Wondering how the scoping will work. According to [these docs](https://developer.spotify.com/web-api/using-scopes/), the 'streaming' scope is only available via the ios/android sdks. Can you still request the scope from your server then pass the token to your sdk? Or do you have to reask for permissions with the 'streaming' scope from the device?

**Comment by lufinkey** [comment]
@michaelmerrill That's now how the scopes work in this module. You specify them in the Spotify.initialize method. Your token server knows nothing about the scopes.

@daegloe I'll look into adding something like this, although I'm not certain how it would work.

**Comment by daegloe** [comment]
@lufinkey I think @michaelmerrill is referring to my setup that I mentioned above. We auth users on a website and then send them to our app. He wants to know if we can ask for the `streaming` scope from the web site so that our access token already has that permission baked in.

@michaelmerrill No you can't currently ask for the `streaming` scope via web auth. But that may be changing. Also, if @lufinkey is able to support this use case, you could auth with `streaming` scope in another app and that token would be useable with this library. So either way, it's a useful capability.

**Comment by cainy393** [comment]
@michaelmerrill If you're still interested in this then Spotify have recently launched a beta [Web Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk/) and my web app is able to request the streaming scope using the regular web API authentication flow.

**Comment by lufinkey** [comment]
Ooh I might just add web support for this module...

**Comment by cainy393** [comment]
@lufinkey The web SDK is very much in beta, it's a little buggy and missing a few features that are in the Android/iOS SDKs. I'd hold off until there's a more stable release, personally.

**Comment by lufinkey** [comment]
good call. It also kinda depends on how similar it is to the native APIs

**Comment by JakeMotta** [comment]
@daegloe Did you ever figure anything out for this? I'm having a similar issue I believe.

**Comment by lufinkey** [comment]
So an update on this. On iOS, the SPTAuth object requires that I also pass a username to it (no idea why), so I need to make a custom Auth object for handling sessions on iOS. Once that's done I can implement this

**Comment by lufinkey** [comment]
This capability has been added in version `1.2.0`. You can use `authenticate` to perform the login flow to get a session without actually logging in, and you can use `loginWithSession` to actually login. `getAuth` and `getAuthAsync` have been changed to `getSession` and `getSessionAsync`.
