### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by BhavanPatel** [lufinkey/react-native-spotify#42]
I am facing error after installing latest "react-native-spotify"
## Error: Cannot read property 'string' of undefined
I didnt imported plugin yet but just installed and run fails...

# **How To Produce** 

1. `npm install --save react-native-spotify`
2. `react-native link`
3. `react-native run-ios`

# **Comes with Error**

- ## **simulator**

![simulator](https://user-images.githubusercontent.com/7195877/36527828-21e0b05e-17d9-11e8-8bb1-ba161784a53f.png)

- ## **React Native debugger**
![consolelog](https://user-images.githubusercontent.com/7195877/36527888-49c6ab50-17d9-11e8-97af-8a2c51633050.png)

# **Environments**

- ## **Package.json**
![packagejson](https://user-images.githubusercontent.com/7195877/36527991-b196b572-17d9-11e8-91ae-6845e1b921b0.png)

- ## **React Native Info**
![reactnativeinfo](https://user-images.githubusercontent.com/7195877/36528012-c3998254-17d9-11e8-8880-8d18dc04b69f.png)

# **Notes**
- Tried all different things to install package like 
`npm install --save https://github.com/lufinkey/react-native-spotify`
`npm install --save @lufinkey/react-native-spotify`
`npm install --save react-native-spotify`
- Tried deleting `node_modules` and install it again
- Tried auto-link and manual-link as given on documentation

Help me out of this issue as soon as possible.
Thanks.

**Comment by lufinkey** [comment]
You've linked the wrong react-native-spotify in your package.json. you linked another dude's package. Mine isn't even on 2.0 let alone 2.0.3

**Comment by BhavanPatel** [comment]
Yes but I tried with  @lufinkey/react-native-spotify which is 1.0.x still same error so go through your package json name

**Comment by BhavanPatel** [comment]
That issue is solved but got another one

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SPTAudioStreamingController", referenced from:
      objc-class-ref in libRCTSpotify.a(RCTSpotify.o)
  "_OBJC_CLASS_$_SPTAuth", referenced from:
      objc-class-ref in libRCTSpotify.a(RCTSpotify.o)
  "_OBJC_CLASS_$_SPTDiskCache", referenced from:
      objc-class-ref in libRCTSpotify.a(RCTSpotify.o)
  "_OBJC_CLASS_$_SPTRequest", referenced from:
      objc-class-ref in libRCTSpotify.a(RCTSpotify.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lufinkey** [comment]
You misunderstand. That's the incorrect package altogether. My package on
npm is @lufinkey/react-native-spotify. Another user owns
react-native-spotify. You are currently using their package, which has a
completely different API and only works for iOS

**Comment by lufinkey** [comment]
Have you run `react-native link` already?

**Comment by BhavanPatel** [comment]
Yes already

**Comment by lufinkey** [comment]
The only thing I can think of is that the spotify sdk submodule didn't get cloned, but if you installed it with `npm install`, that shouldn't be an issue. Check that the `node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK` folder exists and has contents.

**Comment by mpusinhol** [comment]
@BhavanPatel I had that issue. It happened to me because I hadn't copied the frameworks into Xcode and set the frameworks path. Have you done this:

iOS
Manually add the Frameworks from node_modules/react-native-spotify/ios/external/SpotifySDK to Embedded Binaries in your project settings. Then add ../node_modules/react-native-spotify/ios/external/SpotifySDK to Framework Search Paths in your project settings.

Try doing that and check if the erros go away.

**Comment by BhavanPatel** [comment]
@lufinkey and @mpusinhol See the steps I follow to integrate `react-native-spotify`

1. **Npm Install**
![1 npm_i](https://user-images.githubusercontent.com/7195877/36575307-567906a8-1870-11e8-8a97-655f50769e52.png)

2. **React Native Link**
![2 rnlink](https://user-images.githubusercontent.com/7195877/36575313-62e22cc6-1870-11e8-9990-1fdc0c3e51e4.png)

3.  **Check my `package.json` and `node_modules`**
![3 package json](https://user-images.githubusercontent.com/7195877/36575337-78ed807e-1870-11e8-84c1-af94daf8e37f.png)
![4 node_modules](https://user-images.githubusercontent.com/7195877/36575338-7ca7ddea-1870-11e8-9cf2-dc1c194930b3.png)


4. **Now I added manually frameworks to build phases**
- click '+'
![5 buildphase1](https://user-images.githubusercontent.com/7195877/36575389-c56db3ec-1870-11e8-9069-7a28f8a74585.png)
- selected framworks from `node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK` 
![6 buildphase2](https://user-images.githubusercontent.com/7195877/36575399-cab7509c-1870-11e8-8fd5-1ecf083618df.png)
- finish
![7 buildphase3](https://user-images.githubusercontent.com/7195877/36575403-cea0623e-1870-11e8-8aff-41f7d5454293.png)
- added
![8 buildphase4](https://user-images.githubusercontent.com/7195877/36575407-d163286c-1870-11e8-84c9-33f4be67f358.png)

5. **added path in build setting in framework search**
- click '+'
![9 buildsetting1](https://user-images.githubusercontent.com/7195877/36575487-3b9ac62c-1871-11e8-9d7f-48bdb5f1cf3b.png)
- path added
![10 buildsetting2](https://user-images.githubusercontent.com/7195877/36575499-4f00afba-1871-11e8-8563-ebd3741dde6a.png)


6. **Saved all and clean and build project**


7. **Got Error on build**
![11](https://user-images.githubusercontent.com/7195877/36575574-a5197ba2-1871-11e8-9d23-2af13f7ddf95.png)



**NOTE:** before doing all these steps I deleted `node_modules` and `npm install` and project build success but after adding this plugin it fails with the mention error.


Is there anything that I can help you to track where error is? 
Thanks.

**Comment by mpusinhol** [comment]
Try putting $(PROJECT_DIR)/../node_modules.... instead of ../node_modules... in your framework search paths

**Comment by BhavanPatel** [comment]
Ok will check it and let u knw

**Comment by lufinkey** [comment]
Was this ever fixed?

**Comment by BhavanPatel** [comment]
Yes  fixed thanks
