### ISSUE TITLE
Support iOS SDK 'seekTo' method

### ISSUE THREAD

**Issue by daegloe** [lufinkey/react-native-spotify#44]
I see that the Android implementation exports a `seekToPosition` function.

Can we get support for the iOS SDK `seekTo` method?

**Comment by daegloe** [comment]
Ah, never mind. I'll work up a PR.

**Comment by lufinkey** [comment]
This has been added to the dev branch

**Comment by lufinkey** [comment]
This change has been pushed to npm under the new package name `rn-spotify-sdk`
