### ISSUE TITLE
 Error compiling: method toHashMap() does not exist on ReadableMap class

### ISSUE THREAD

**Issue by vadhack** [lufinkey/react-native-spotify#45]
Please help
Error when run: react-native run-android
Using: React-native version 0.45.1

`.../node_modules/@lufinkey/react-native-spotify/android/src/main/java/com/lufinkey/react/spotify/Utils.java:24: error: cannot find symbol
                HashMap<String, Object> map = params.toHashMap();
                                                    ^
  symbol:   method toHashMap()
  location: variable params of type ReadableMap
1 error
:react-native-spotify:compileReleaseJavaWithJavac FAILED
`

**Comment by lufinkey** [comment]
You may need to downgrade for now. I'll add this as another item for the next release.

**Comment by lufinkey** [comment]
Have you made sure to clear your node modules and unlink any old libraries? It's very likely your Android project is still pointing to a newer version of react native

**Comment by vadhack** [comment]
Yes, i uninstall the module react-native-spotify because i cant use it, i cant find the way to make it work, thanks

**Comment by lufinkey** [comment]
OK

**Comment by lufinkey** [comment]
After updating the react native version to the latest, I don't seem to have this problem, so I'm going to close this issue
