### ISSUE TITLE
Unable to find explicit activity class mypackage/com.lufinkey.react.react.spotify.AuthActivity

### ISSUE THREAD

**Issue by Cetzcher** [lufinkey/react-native-spotify#46]
I get a red screen when calling Spotify.login(...) in my JS code and I cannot figure out why. I built the example project and it worked fine. I created a new project installed react-native-spotify like described in the readme and it worked fine as well. However when I use it in the project im currently developing I get stuck with the error. 

I compared app/buidl.gradle and build.gradle of the example project. All the versions e.g build tools line up. The module itself is linked properly since I import the module just fine, i can even call Spotify.initialize (like in the example project). The react and react-native versions are compatible as well.

So the problem has to do with the fact that login is trying to start the overlay activity which somehow cannot be found the exact error message is: Unable to find explicit activity class mypackage/com.lufinkey.react.react.spotify.AuthActivity; have you declared this activity in your AndroidManifest.xml?

My AndroidManifest: 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"
    package="com.votemmusic"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.VIBRATE"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
      tools:node="replace">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```
Other infos:
My Application:           
compileSdkVersion 23         
buildToolsVersion "23.0.2"    
classpath 'com.android.tools.build:gradle:2.2.3' ( I created a project with this gradle version and it worked)
"react": "16.0.0"
"react-native": "0.50.4"

Any recommendations what I should do to get this to work? Is this a conflict with other dependencies? I have tried to add the activity to my AndroidManifest but this just leads to a total crash of the app.
Thanks in advance!

**Comment by lufinkey** [comment]
Did you explicitly call react native link? This just sounds like it wasn't linked properly

**Comment by Cetzcher** [comment]
Yes I did, I tried manually modifying settings.gradle and build.gradle as well, that's why I'm so clueless. I also tried to modify the node_moduels directly just in case of any naming conflicts

**Comment by lufinkey** [comment]
It might be your react native version maybe? try 0.41.2. Other than that, I'm not really sure.

**Comment by Cetzcher** [comment]
I'll try when I get to work, my other idea was to use the dev branch of this repo. I'll update the issue with my findings. Still, thanks a lot.

**Comment by lufinkey** [comment]
Can you see if the latest version works?
