### ISSUE TITLE
iOS build fails with 'too many errors emitted, stopping now'

### ISSUE THREAD

**Issue by smaradona** [lufinkey/react-native-spotify#47]
Hey there! I have followed the installation steps:

1. npm install --save @lufinkey/react-native-spotify
2. react-native link @lufinkey/react-native-spotify
3. Manually add the Frameworks from node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK to Embedded Binaries in your project settings.
4. Then add ../node_modules/@lufinkey/react-native-spotify/ios/external/SpotifySDK to Framework Search Paths in your project settings.

And when I try to build in Xcode I'm getting lots of errors/warnings in RCTSpotify.m

![screen shot 2018-03-17 at 11 33 48 am](https://user-images.githubusercontent.com/1944996/37556654-bb794478-29d7-11e8-9fd6-634ad379bfb0.png)

Any idea what I'm doing wrong? Thanks a lot in advance!

react-native: 0.44.3

**Comment by lufinkey** [comment]
If you're trying to build to react native Spotify xcode project alone, it won't build unless it's in the context of a full react native project

**Comment by smaradona** [comment]
Hello! Thanks for your reply! Yes, I'm trying to use react-native-spotify in the context of my full react native project. Any ideas?

**Comment by lufinkey** [comment]
Did you install from the GitHub project, or did you install `npm install --save @lufinkey/react-native-spotify

**Comment by smaradona** [comment]
I first tried using yarn but the `node_modules/react-native-spotify/ios/external/SpotifySDK` was empty. Then I installed it via `npm install --save @lufinkey/react-native-spotify`

**Comment by lufinkey** [comment]
Hm. I'm honestly not sure. I'd have to look into it

**Comment by lufinkey** [comment]
try updating react-native to the latest version

**Comment by smaradona** [comment]
Sorry for the delay, I just tried updating react-native to the latest version and the build succeeds. Thanks!
