### ISSUE TITLE
display_name returns null

### ISSUE THREAD

**Issue by mrcolo** [lufinkey/react-native-spotify#48]
Hey! I'm trying to work with the example provided on the repo. 

I got this output. It looks like my username shows up under id, rather than display_name. Am I making a mistake?

`{ product: 'premium',
  external_urls: { spotify: 'https://open.spotify.com/user/MYUSERNAME' },
  followers: { href: null, total: 0 },
  country: 'US',
  images: [],
  id: 'MYUSERNAME',
  href: 'https://api.spotify.com/v1/users/MYUSERNAME',
  display_name: null,
  type: 'user',
  uri: 'spotify:user:MYUSERNAME' }`

**Comment by lufinkey** [comment]
This is not an issue with the module, but with the Spotify API itself. The module is only returning the JSON data it's getting from the Spotify API endpoints

**Comment by mrcolo** [comment]
Oh alright! Thanks for your help!
