### ISSUE TITLE
Setting up refresh/swap token server

### ISSUE THREAD

**Issue by donghee214** [lufinkey/react-native-spotify#49]
Hi! 

So I set up my own server with its own url using the server implementation example as a template. When I however use this url+/refresh and url+/swap for tokenRefreshURL and tokenSwapURL props for the options body it doesn't even initialize. Trying to catch the error, this is all I'm getting:

03-22 21:35:47.184  6926  7380 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
03-22 21:35:47.184  6926  7380 W ReactNativeJS: Error: Unable to send request

Any help is appreciated,

Thank you!

**Comment by lufinkey** [comment]
Look at the README on the dev branch. The function returns a promise, which you need to catch errors from.

**Comment by donghee214** [comment]
So the caught error is simply: 

{ [Error: Unable to send request] framesToPop: 1, code: 'HTTPRequestFailed' }. 

Does this mean my server for refresh and swapping is set up wrong?

**Comment by lufinkey** [comment]
Have you tried manually sending requests to your server to see if they work?

**Comment by donghee214** [comment]
Do you have any tips on how to test this? I'm relatively new to backend, and I'm unsure what params to even pass in with the POST. The code for my server however is identical to the one you provided in the example-server if that's any help.

Thank you

**Comment by lufinkey** [comment]
Postman is a good program to use for this. You can also read about the
Spotify token swap parameters [here](
https://developer.spotify.com/technologies/spotify-ios-sdk/token-swap-refresh/
)

**Comment by donghee214** [comment]
Thanks a bunch, so I've installed postman and tried doing some requests, but I keep getting a request timed out error every time. This leads me to believe I've set up my server incorrectly.

Is setting up this "server" any different from the process of pushing other web apps online? (With the exception of the example-server not having a public directory)

**Comment by lufinkey** [comment]
It's just a simple node app. You just run npm start in the directory and
connect to it with your computer's local IP, or remote IP if you're
accessing it from outside your network and you've forwarded the connection.

Please don't ask for help with basic backend setup because that is not a
bug or enhancement with the module.
