### ISSUE TITLE
Add iOS / Android specific options to README

### ISSUE THREAD

**Issue by pedroslopez** [lufinkey/react-native-spotify#51]
So I'm using [react-native-music-control](https://github.com/tanguyantoine/react-native-music-control) to add control center / lockscreen controls to my app, but there's a limitation in iOS where [MPNowPlayingInfoCenter](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter) only shows the controls on a real device if it has a non mixable audio session category.

Digging around in this module's native code I found in RCTSpotify.m line 200 the following:
```
_audioSessionCategory = iosOptions[@"audioSessionCategory"];
if(_audioSessionCategory == nil)
{
	_audioSessionCategory = AVAudioSessionCategoryPlayback;
}
```

My question is, what audio session category is it using and can this be changed without other effects in the app? Forcing it to use AVAudioSessionCategoryPlayback allows the control center and lockscreen controls to work perfectly fine, I just want to know if there's a reason this is here.

Thanks in advance.

**Comment by lufinkey** [comment]
You can pass any audio session category you want to use as an option in the initialize method, using the ios.audioSessionCategory property.

**Comment by lufinkey** [comment]
The default category is `'AVAudioSessionCategoryPlayback'`

**Comment by pedroslopez** [comment]
huh, oddly enough I set the code back to what it was (using the ios options) and it seems to be working.

In any case, like you said in the title, it'd be nice to know the options we can set in the initialize method.
