### ISSUE TITLE
Cannot add new playlist via sendRequest

### ISSUE THREAD

**Issue by justin-segler** [lufinkey/react-native-spotify#52]
I am trying to add a new playlist to my Spotify via the sendRequest method. 

This is my code: 

```
Spotify.sendRequest(
    `https:\/\/api.spotify.com\/v1\/users\/${this.props.spotifyId}\/playlists`,
    'POST',
    {
        name: 'test'
    },
    true,
    (result, error) => {
          if (error) {
              console.log(error);
          } else {
              console.log(result);
          }
    }
);

```
But this is the error I get back:

```
{message: "Service not listed", domain: "com.spotify.web-api", code: 404}
```

Anyone able to do this successfully?

**Comment by lufinkey** [comment]
If you look at the documentation for sendRequest, you'll see that you pass in the endpoint. Not the full URL.

**Comment by justin-segler** [comment]
I see. I tried it with this but it still throws an error:

```
Spotify.sendRequest(
        `https:\/\/api.spotify.com\/v1\/users\/\{userId\}\/playlists`,
        'POST',
        {
          'userId': this.props.spotifyId,
        },
        true,
        (result, error) => {
          if (error) {
            console.log(error);
          } else {
            console.log(result);
          }
        }
      );
```

```
{message: "unsupported URL", domain: "NSURLErrorDomain", code: -1002}
```

**Comment by justin-segler** [comment]
Also, is there a way to add a request body or does the send request method only take in request params?

**Comment by lufinkey** [comment]
You just sent the same code. Please read the documentation before opening issues. As I said before, you aren't passing in the full spotify URL. You should be passing in the endpoint. Example: `'v1/me'`

**Comment by justin-segler** [comment]
Just updated my comment

**Comment by justin-segler** [comment]
Getting this error with the above code. 

```
{message: "Insufficient client scope", domain: "com.spotify.web-api", code: 403}
```

**Comment by lufinkey** [comment]
Are you printing the string to make sure it is the correct endpoint?

**Comment by justin-segler** [comment]
Are you able to run that code and have it work?

**Comment by lufinkey** [comment]
I believe the error message you are getting should tell you the error. You haven't requested the scope needed for that endpoint

**Comment by lufinkey** [comment]
Read what the error message says. Go look at available Spotify scopes and see which one you are missing in your initialize method for that endpoint.

**Comment by justin-segler** [comment]
I think this is something with the oauth token

**Comment by justin-segler** [comment]
What scope do I need to add?

**Comment by justin-segler** [comment]
Got it. You needed to add 'playlist-modify-public'

**Comment by lufinkey** [comment]
Great.
