### ISSUE TITLE
Does not play songs added to playlist after calling playURI

### ISSUE THREAD

**Issue by justin-segler** [lufinkey/react-native-spotify#53]
I have my code such that I can create a new playlist on Spotify and add songs to it. However, I add my songs to the playlist and call playURI on the playlist ID, but when I go to add new songs to the existing playlist, the playURI stops playing the songs as soon as it reaches the end of the first list of songs I queued up before calling playURI. For example, if I queue song1 and song2 to the playlist, call playURI on the playlist ID, and then add song3 to the playlist while it is playing, the playlist only plays through song1 and song2 and does not play song3. Any ideas?

**Comment by lufinkey** [comment]
This is an issue with the native Spotify SDK. If you're trying to implement a queue, you should probably just rely on the new events. Otherwise, you could always just start playing the playlist at the next song when the current song ends using events.

**Comment by justin-segler** [comment]
How would I use events to check when the current song is finished?

**Comment by lufinkey** [comment]
Please just read the README section on the available events. It tells you exactly what you need to know.

**Comment by justin-segler** [comment]
I'm sorry for being difficult, but which event would be used to notify that the player has finished playing a song? All I see is trackChange, play, and pause - none of which seem to denote that a song has finished playing.

**Comment by lufinkey** [comment]
It is the `'trackDelivered'` event. I've updated the wording to be clearer, as it was previously just copied directly from the spotify docs.
