### ISSUE TITLE
Include in README that this is only for premium users

### ISSUE THREAD

**Issue by Ilario17** [lufinkey/react-native-spotify#56]
Hi,

The login() method return always false. 
I do the login inside the webview and when I come back on app the boolean "loggedIn" is false.

I tried it on iOS Simulator 9.3, and a free Spotify account.

I do not know where to start to understand the reason for this problem.

**Comment by lufinkey** [comment]
This framework is only available for Spotify premium users

**Comment by lufinkey** [comment]
Otherwise it doesn't work

**Comment by Ilario17** [comment]
Oh, ok.. is this a spotify sdk problem? 

however, writing it in Readme would not be bad ..

**Comment by lufinkey** [comment]
[see here](https://github.com/spotify/ios-sdk/issues/706)

**Comment by lufinkey** [comment]
I will add it to the READMe

**Comment by Ilario17** [comment]
Thank you for your time. I think it's definitely absurd that a premium user is required.

That you know, there is at least one way to open the spotify app from a trackURI?

Thanks
Ilario

**Comment by lufinkey** [comment]
If it's not documented in this module, then I probably don't know. Check
the Spotify Android SDK and iOS SDK docs.
