### ISSUE TITLE
getAuthAsync resolves by returning an array

### ISSUE THREAD

**Issue by rgehan** [lufinkey/react-native-spotify#57]
`getAuth` returns an object, but `getAuthAsync` returns an array containing the object.

It's not really an issue, but it would be coherent to have both method resolve the same way. I don't think there are other methods returning an array like this, so that might be a mistake.

Thanks for that great lib!

**Comment by lufinkey** [comment]
Ah woops. That's leftover from before I switched to promises.

**Comment by lufinkey** [comment]
I'll fix it

**Comment by lufinkey** [comment]
fixed
