### ISSUE TITLE
expireTime is not accurate

### ISSUE THREAD

**Issue by edwardpayton** [lufinkey/react-native-spotify#58]
Hi, thanks for this module, it is fantastically easy to work with and works very well.

I am having an issue that I can't seem to understand - the token object expiresTime.

I've set up a token refresh server, and my React Native app is communicating with it. Printing out the result of the getAuthAsync() method to the console shows me this token object:

<pre>
accessToken: "BQBT-L...l8EkqQ"
expireTime: 917928876
refreshToken:"93cc60...100507"
</pre>

The Spotify Authorisation Guide says on successfully renewing the token, the response body includes:
> expires_in | int | The time period (in seconds) for which the access token is valid.

The example in the guide shows this to be 3600, which is one hour. 

So what does the expiresTime parameter refer too? I have been trying to work it out, thinking it may represent the actual expiry time (current time + 1 hour) but that doesn't seem to be correct. What am I missing here?

My React Native project setup is as follows:

<pre>
"android": "0.0.8",
"react": "^16.2.0",
"react-native": "^0.53.3",
"react-navigation": "^1.5.8",
"react-redux": "^5.0.7",
"redux": "^4.0.0",
"redux-logger": "^3.0.6",
"redux-persist": "^5.9.1",
"redux-thunk": "^2.2.0",
"rn-spotify-sdk": "~1.1.0"
</pre>

**Comment by lufinkey** [comment]
If you look at the README documentation for the getAuth method and getAuthAsync method, you'll see that it says it returns an *Auth* object. If you look at the [documentation for the *Auth* object](https://github.com/lufinkey/react-native-spotify#types) in the same README, you'll see that it explains exactly what expireTime refers to

**Comment by edwardpayton** [comment]
Thanks for coming back to me.

That makes sense, and I did read it before hand, however the expireTime number is not a future date.

According to epochconverter.com, 917928876 is GMT: Tuesday, 2 February 1999 04:14:36. Calling the API again a few minutes ago returned 999377424 which is GMT: Saturday, 1 September 2001 20:50:24.

**Comment by lufinkey** [comment]
What platform are you on?

**Comment by edwardpayton** [comment]
MacOS High Sierra

**Comment by lufinkey** [comment]
I mean what platform are you developing for, not what you're developing on.
Android or iOS?

**Comment by edwardpayton** [comment]
Oh, Android. SDK v.23 (Marshmallow)

**Comment by lufinkey** [comment]
I'll investigate this when I get the chance

**Comment by sslash** [comment]
Any updates on this? I also get slightly confused by the same issue

**Comment by lufinkey** [comment]
Sorry I've had barely any time to work on this. At some point I'm going to sit down and try to get all of the issues fixed at once but I haven't gotten around to it yet.

**Comment by sslash** [comment]
Cool! I've also noticed that the expireTime is one hour into the future. Is there a way to set this? Or if it's a bug, could you guide me to a place to debug this? Would love to help out!
