### ISSUE TITLE
Make initialize throw an error if redirectURI is not given

### ISSUE THREAD

**Issue by bsiddiqui** [lufinkey/react-native-spotify#64]
When I try and login, I see a blank web view. The only param I'm passing to initialize is `clientID`

**Comment by lufinkey** [comment]
You need a redirectURI

**Comment by bsiddiqui** [comment]
@lufinkey ah I had it setup in my Spotify Dashboard but missed it in the initialize config because it's not listed as required in the Readme:
![screenshot 2018-06-28 20 15 05](https://user-images.githubusercontent.com/2721959/42071439-09ffeca8-7b10-11e8-929c-bef614ccddfb.png)

I'm happy to update the docs.
