### ISSUE TITLE
npm WARN rn-spotify-sdk@1.1.1 requires a peer of react-native@^0.53.3 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by solanki12** [lufinkey/react-native-spotify#67]
it creates issues when using on latest framework of react native.

**Comment by solanki12** [comment]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SPTAudioStreamingController", referenced from:
      objc-class-ref in libRNSpotify.a(RNSpotify.o)
  "_OBJC_CLASS_$_SPTAuth", referenced from:
      objc-class-ref in libRNSpotify.a(RNSpotify.o)
  "_OBJC_CLASS_$_SPTDiskCache", referenced from:
      objc-class-ref in libRNSpotify.a(RNSpotify.o)
  "_OBJC_CLASS_$_SPTRequest", referenced from:
      objc-class-ref in libRNSpotify.a(RNSpotify.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lufinkey** [comment]
This means that libSpotify.a is not linked in the xcode project for your react native app

**Comment by lufinkey** [comment]
It may also mean that the Spotify frameworks are not linked in your xcode project. Either way it looks like you haven't run the required `react-native link` command.

**Comment by solanki12** [comment]
![screen shot 2018-07-20 at 5 56 53 pm](https://user-images.githubusercontent.com/18504965/43003655-9d496c86-8c46-11e8-85d2-79c74d208bf0.png)
![screen shot 2018-07-20 at 5 56 11 pm](https://user-images.githubusercontent.com/18504965/43003658-9e9ace22-8c46-11e8-8679-332befc7785f.png)
![screen shot 2018-07-20 at 5 56 19 pm](https://user-images.githubusercontent.com/18504965/43003659-9ed974f6-8c46-11e8-9520-6fb377554fbf.png)

react-native link rn-spotify-sdk
react-native link react-native-events
this is what i have configured, can u tell me what is missing ?
Thanks

**Comment by lufinkey** [comment]
That should be all you have to do

**Comment by solanki12** [comment]
But still em getting this error

Regards
Alishah Solanki

**Comment by lufinkey** [comment]
Please try adding the required frameworks to "Linked Libraries and Frameworks"

**Comment by solanki12** [comment]
thanks, i already fixed that issue.
