### ISSUE TITLE
Add methods for getting info about the current user

### ISSUE THREAD

**Issue by XavierColombel** [lufinkey/react-native-spotify#7]
I'm trying to get user infos. Any hint?

**Comment by lufinkey** [comment]
You can use the [sendRequest](https://github.com/lufinkey/react-native-spotify#metadata-methods) method to send a general request to the Spotify API. I haven't implemented all of the API methods as their own functions yet, so you can check out their endpoint reference [here](https://developer.spotify.com/web-api/endpoint-reference/)

Now that I think about it, though, there is not currently a way to get info about the currently logged in user, so I'll look into adding that

**Comment by lufinkey** [comment]
Actually, you can get the current user's info with [this endpoint](https://developer.spotify.com/web-api/get-current-users-profile/), so use the sendRequest method for that

**Comment by lufinkey** [comment]
I've added a convenience method for v1/me. You can use the getMe function

**Comment by robertoost** [comment]
Came in very handy, just when I needed it! Good progress.
