### ISSUE TITLE
Example project not working

### ISSUE THREAD

**Issue by dvdhoek** [lufinkey/react-native-spotify#74]
I tried to set everything up and followed instructions. I got the following error: 

`undefined is not an object (evaluating 'nativeModule._registerAsJSEventEmitter')
`
I can reproduce the same error with the example project, on first build. I guess I'm missing something, but I can't figure out what.

**Comment by AlexLaRochelle** [comment]
Same thing for me..

**Comment by AlexLaRochelle** [comment]
@dvdhoek I fixed part of it, in xCode, I had the folder node_modules/rn-spotify-sdk/ios/external/SpotifySDK in Linked Frameworks, not the 3 .frameworks (I guess this is a silly mistake on my part). Now Im able to see the log in button and everything, but after the login it says 

"undefined is not a function (near '..._reactNavigation.NavigationActions.reset...')

Getting on that now..

**Comment by dvdhoek** [comment]
Ok, could you tell me your setup? Maybe I'm missing something. I've checked but the frameworks are added correctly as far as I can tell. Maybe it has to do with xCode 10?

**Comment by dvdhoek** [comment]
After a lot of searching around I'm pretty sure the issue lies with Xcode 10. Also, I had to run react-native link react-native-events seperate, as I as getting another error on this.

**Comment by lufinkey** [comment]
I believe the fix is what @dvdhoek mentioned. Try running `react-native link react-native-events` and `react-native link react-native-spotify` separately

**Comment by dvdhoek** [comment]
Yes for me that was the issue. I also had issues with an update of Xcode,
can’t remember what caused this issue.

**Comment by mustafadane** [comment]
Thanks for your replies! unfortunately it did not work. Before doing it, i deleted the whole node modules files. did npm install while rn-spotify-sdk and react-native-events are in my dependencies in package.json. Then I did the linking separately, events first. I don't know what to do now. Your library looks pretty good, thanks for making it. So I really want to use it.

I am also getting a linter error or suggestion. I don't know if I have some other error going on. I added a screenshot for that error. 
![spotify](https://user-images.githubusercontent.com/41445860/48306429-fbf81b00-e4fd-11e8-83f3-714a1d93ae43.JPG)

**Comment by mustafadane** [comment]
I restarted my computer and now it's working!!! Thanks so much y'all!!! Linking again worked nicely. If someone else reads this later, make sure to delete android, ios folders, then eject then link. Otherwise, nothing works. 

So I guess, you can close this issue now. Again, thanks for helps and thanks for this awesome library!
