### ISSUE TITLE
NavigationActions.reset removed in v2

### ISSUE THREAD

**Issue by linuxboss182** [lufinkey/react-native-spotify#76]
Found a bug in the sample code which related to NavigationActions.reset being removed in v2. On a successful login we get an error message saying cannot find reference to undefined.

**Comment by lufinkey** [comment]
Is there something that replaces it or did they just straight up remove it?

**Comment by linuxboss182** [comment]
They removed it from NavigationActions and you need to use StackActions along side it to access the  .reset, its just a two line change. See https://stackoverflow.com/questions/50781080/navigationactions-reset-is-not-a-function
