### ISSUE TITLE
sendRequest with params fails on Android

### ISSUE THREAD

**Issue by davidskaarup** [lufinkey/react-native-spotify#79]
When I try to use params to set `limit` and `offset` it works perfectly on iOS but on Android I get the following error:

```
Error: Invalid response format
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:72
```

My code looks like this:

`Spotify.sendRequest("v1/me/playlists", "GET", { offset: 1, limit: 2 }, false)`

If I call `sendRequest` with no params it works fine on both platforms:

`Spotify.sendRequest("v1/me/playlists", "GET", null, false)`

Am I doing something wrong?

**Comment by lufinkey** [comment]
I have it parse the strings and remove any trailing zeroes if the number has nothing but zeroes in the decimal places. The fix is in the `dev` branch. I'll close this once it's published to npm
