### ISSUE TITLE
Error linking the sdk on the android platform

### ISSUE THREAD

**Issue by AndreBastos23** [lufinkey/react-native-spotify#8]
Hello,

when adding the `flatDir {
            url "$rootDir/../node_modules/react-native-spotify/android/libs"
        }` to the build.gradle, i got this error Gradle DSL method not found 'google()'.
Do you have any idea what do i need to to to fix this? This is because my grade version doesnt support this yet. (Its a brand new react-native project).

**Comment by lufinkey** [comment]
Yeah somebody recently merged adding the google repository to the gradle. I'll look into it

**Comment by lufinkey** [comment]
It seems to build fine for me. Try updating your project's gradle version to 3.0.1, or see the example project within the app

**Comment by AndreBastos23** [comment]
That's what i did to fix the issue, but you should make sure your library works with the defaults of react-native(build gradle 2.3.1).
But thanks anyway, let's hope i can build what i want to do using your library :)
