### ISSUE TITLE
Jest TypeError: Cannot read property '__registerAsJSEventEmitter' of undefined

### ISSUE THREAD

**Issue by AlexLaRochelle** [lufinkey/react-native-spotify#80]
When i'm trying to use jest for a simple test with Spotify.playURI, im getting: 

TypeError: Cannot read property '__registerAsJSEventEmitter' of undefined

at Object.<anonymous>.RNEvents.register (node_modules/react-native-events/index.js:62:21)
      at Object.<anonymous> (node_modules/rn-spotify-sdk/src/Spotify.js:7:28)
      at Object.<anonymous> (node_modules/rn-spotify-sdk/src/Queue.js:3:51)
      at Object.<anonymous> (node_modules/rn-spotify-sdk/index.js:2:49)

As if Spotify in RNEvents.register(Spotify); in Spotify.js was null? My app is running fine, im only getting this in jest. Any idea why?

**Comment by lufinkey** [comment]
No idea why that would only be happening in jest

**Comment by satinjeet** [comment]
Same is happening to me. confirmed that is happens at the point where the package is included.

![image](https://user-images.githubusercontent.com/823011/50260651-f16f5200-03d6-11e9-8bb7-7fbf8a5e20a5.png)

**Comment by patrice4github** [comment]
I don't think it's Jest related. I have this error right after importing Spotify:

`import Spotify from 'rn-spotify-sdk';`

<img width="1028" alt="Screen Shot 2019-08-30 at 8 48 09 AM" src="https://user-images.githubusercontent.com/1727358/64022016-3b323f80-cb03-11e9-8af9-14cf2a08f6ad.png">

**Comment by apperside** [comment]
hello @patrice4github , I am experiencing the same issue, how did you solved it?
