### ISSUE TITLE
refreshURL never being hit

### ISSUE THREAD

**Issue by neilspurgeon** [lufinkey/react-native-spotify#81]
Everything is working fine, but I can't get it to refresh the token. I've tested my refresh endpoint separately and it works fine, but the module never calls it. After the access token expires `Spotify.initialize()` always returns false.

I have everything pretty much setup just like the example right now. Is there anything else I need to do to refresh the token?

```
componentDidMount() {
  if(!Spotify.isInitialized()) {
    const spotifyOptions = {
      "clientID": SPOTIFY_CLIENT_ID,
      "sessionUserDefaultsKey": "SpotifySession",
      "redirectURL": "queueapp://spotify-redirect",
      "scopes": ["user-read-private", "playlist-read", "playlist-read-private", "streaming", "user-library-read"],
      "tokenSwapURL": QUEUE_API_URL + "/api/v1/spotify/authenticate",
      "tokenRefreshURL": QUEUE_API_URL +  "/api/v1/spotify/refresh_token",
  };
  
  Spotify.initialize(spotifyOptions).then((loggedIn) => {
    this.setState({spotifyInitialized: true});
    if(loggedIn) {
      // logged in
    }
  })
    .catch((error) => {
      Alert.alert("Error", error.message);
    });
  }
}
```

**Comment by lufinkey** [comment]
What platform is this for?

**Comment by neilspurgeon** [comment]
This is on iOS

**Comment by lufinkey** [comment]
Are you saying it just expires after an hour and never refreshes?

**Comment by neilspurgeon** [comment]
Yeah from what I can tell it never tries to refresh. I assumed it was supposed to handle refreshing, but a manual method would be great too. 

Thanks! This has been really great to work with.

**Comment by lufinkey** [comment]
It does try when the player auto logs out, and when you call initialize, but I'm not certain why it's not working like it should. Either way, auto-refreshing will be added soon

**Comment by lufinkey** [comment]
update. Just added an auth renewal timer on iOS. This issue should be solved completely on the `dev` branch now

**Comment by neilspurgeon** [comment]
The dev branch is working for me now if I reload the app or re-initialize the module after after the token expires. 

The timer isn't working for some reason, but I'm not sure a timer is best way to handle this anyways. I think it would be better to check if the token is expired on each call and refresh it then if it is. Could you still provide a manual refresh method and make the timer optional?

**Comment by lufinkey** [comment]
Yeah I'll look into both of those things
