### ISSUE TITLE
PlayURI always plays at the start on ios

### ISSUE THREAD

**Issue by AlexLaRochelle** [lufinkey/react-native-spotify#83]
I'm currently a little lost, as I don't understand why the Spotify.playURI works perfectly on Android, but on IOS, the "startPosition" does not seem to matter. It plays the correct track specified by the uri, but it always starts the song at 0 seconds. I have a hard time wrapping my mind around why that would be the case, since it's only a request to a web api. Any ideas?

**Comment by lufinkey** [comment]
This seems like it might be a bug with the native iOS streaming sdk. I'm basically just passing the start position directly to the playSpotifyUri:startingWithIndex:startingWithPosition: method. I would check the open issues on the Spotify SDK and see if anyone's opened an issue about that.

The unfortunate part is that Spotify has basically stopped developing their streaming SDK in favor of their remote SDK, which doesn't allow a lot of features, so if it is due to that, there's not much I can do.

**Comment by lufinkey** [comment]
I am also using NSUInteger as the parameter type on iOS, and it might be that I need to use NSNumber. I'll look into it more when I have the chance

**Comment by AlexLaRochelle** [comment]
Alright thanks, I might just implement the new remote SDK natively on iOS and make the playURI call to that then..

**Comment by AlexLaRochelle** [comment]
I also looked at the streaming-sdk, from what I can see, you're using the right parameter types for every parameter (especially the one that I care for, startingWithPosition, that uses a NSTimeInterval). I'll create an issue on their repo to see if anyone knows about it.

**Comment by AlexLaRochelle** [comment]
After further testing, I managed to make it work by using milliseconds instead of seconds for iOS. Seems odd that its different depending on the plaftorm, but for now I'll be using a simple fix:

```
const platformMultiplier = Platform.select({
                    ios: 1000,
                    android: 1,
                });
```

**Comment by lufinkey** [comment]
I've fixed this on iOS

**Comment by AlexLaRochelle** [comment]
Hi @lufinkey ! I'm currently in the last year of my CS degree and was interested doing a project with react-native using you and/or cjam's library. Obviously I'd prefer using cjam's as it's using the more recent version of the Spotify mobile SDK, but might require me to help him with the Android support. Could you reach out to me at alexandre.larochelle4@usherbrooke.ca so that I could clarify my situation and see what would be feasible for me to do in terms of contribution (since you did the Android support for this library)? Thanks!
