### ISSUE TITLE
Setting volume with sendRequest is not working

### ISSUE THREAD

**Issue by davidskaarup** [lufinkey/react-native-spotify#84]
I'm trying to set the volume of the Spotify player as described in the API reference [here](https://developer.spotify.com/console/put-volume/).

```
Spotify.sendRequest(
  "v1/me/player/volume",
  "PUT",
  { volume_percent: 50 },
  false
)
```

I have also added the `user-modify-playback-state` scope.

But I'm getting errors on both iOS and Android:

On iOS I get `The data couldn’t be read because it isn’t in the correct format`

On Android I get `Required parameter volume_percent missing` even though it is included in the request.

Is there any way to solve this?

**Comment by lufinkey** [comment]
You're passing `false` for the JSON body even though the request requires a JSON body. Try passing `true`

**Comment by davidskaarup** [comment]
Now I get `Required parameter volume_percent missing` on both platforms

**Comment by dcvz** [comment]
@davidskaarup this PR https://github.com/lufinkey/react-native-spotify/pull/97, should allow you to use the `setVolume` method on both iOS & Android

**Comment by lufinkey** [comment]
The `setVolume` method should work for setting volume. On android, this must be manually enabled with `{"android":{"useCustomController": true}}` options set in the `initialize` options
