### ISSUE TITLE
Allowing Spotify "freemium" users to login & search music

### ISSUE THREAD

**Issue by JakeMotta** [lufinkey/react-native-spotify#86]
Hi all, thanks for the awesome library!

I know that Spotify recently updated their SDK to allow free users most everything but playback, but are there any plans at the moment to integrate those changes?

I've already got this library installed and working properly, but I was wondering if there's any chance of Spotify "freemium" users to be able to login and search music (not playback though)?

**Problem:**
I need to get an access_token for the Spotify "freemium" users on my app, but I'm not sure how to go about that right now without trying to integrate Spotify's SDK directly.. Any ideas on how I can accomplish this?

Thanks!

**Comment by shariqs** [comment]
This would be really valuable. 
I don't mind making the changes myself. Is there anywhere in the code that I should look in order to start?

**Comment by lufinkey** [comment]
The new SDK is very different than the one currently being used. It "remotes" to the official Spotify app and controls it, so there are more limitations on what can be done with it. Also, there is already an open issue for getting the new SDK implemented (#78), so I'm going to close this
