### ISSUE TITLE
error when run-android: cannot find symbol

### ISSUE THREAD

**Issue by nicolas-rohricht** [lufinkey/react-native-spotify#88]
Hi,

I'm gettin the error "cannot find symbol" when executing the react-native run-android.

![spotify error](https://user-images.githubusercontent.com/38505703/50895614-b49ee580-13ed-11e9-9521-781d5103cda1.png)

My RN version: 0.57.8

Both of these commands were executed succefully, with no errors
react-native link react-native-events
react-native link rn-spotify-sdk

Any idea what's going on?

**Comment by lufinkey** [comment]
Try building with Android Studio instead of running `react-native run-android`. Gradle is very buggy and broken and I've found that Android Studio sometimes requires a couple restarts before it works correctly

**Comment by nicolas-rohricht** [comment]
I tried to do that and got this error: 

![image](https://user-images.githubusercontent.com/38505703/50906394-26862780-140c-11e9-8670-29e7a797b053.png)

When you said "building with Android Studio" you mean clicking the play button to run the project inside on an emulator or device from Android Studio right?

**Comment by nicolas-rohricht** [comment]
Any idea?

**Comment by lufinkey** [comment]
It seems like it's trying to import RNSpotifyPackage from the Spotify authentication library, which doesn't make any sense. Either `react-native link` messed up somewhere along the line or you let the IDE autoimport something you didn't mean to. Either way, RNSpotifyPackage's location should be `com.lufinkey.react.spotify.RNSpotifyPackage`

**Comment by nicolas-rohricht** [comment]
Hmm. Weird.

I uninstalled and installed again and got the same errors :(

What's the gradle version are you using?

**Comment by lufinkey** [comment]
3.2.1

**Comment by nicolas-rohricht** [comment]
Hmm.

I'm using 4.4.

**Comment by nicolas-rohricht** [comment]
Hmm.

I'm using 4.4 🤔

**Comment by lufinkey** [comment]
Well I guess try using 3.2.1, although it's still really weird that it's trying to import that class in that way.

**Comment by lufinkey** [comment]
Gradle is kinda the worst. I've never had an easy time with it.

**Comment by lufinkey** [comment]
I've updated to 4.6 and my project still seems to be working

**Comment by nicolas-rohricht** [comment]
Right!

I'm creating a new project from zero and I will try to install react-native-spotify.

As soon as I have the result, I come to a report.

**Comment by nicolas-rohricht** [comment]
Bad news :(

Didn't get success on my tests.
I tried both situations:

1 - Created an new project from zero and added react-native-spotify. Passed on gradle and I tried do install on device. Got error.

2 - Upgraded Gradle to 4.6. Got error.

In both cases, the same error that I described on my first post, happened again.

**Comment by lufinkey** [comment]
Is it the same error?

**Comment by lufinkey** [comment]
Since it's the same error, that makes me think it's a bug in `react native link` potentially? Would you be opposed to uploading a zip of your project somewhere?

**Comment by nicolas-rohricht** [comment]
sure.

I will do that.
I'm gonna upload the project and bring a shareable link.

**Comment by nicolas-rohricht** [comment]
Here is the project...

https://www.dropbox.com/s/sqh2dda9te1fkeh/finalspotifytest.zip?dl=0

**Comment by nicolas-rohricht** [comment]
Hi.
Have you tried to run the project or analyze what is happening?

Thanks for while.

**Comment by lufinkey** [comment]
Sorry I haven't gotten a chance to look at this yet. Meant to take some time this weekend and forgot. I'll try to look tonight

**Comment by sycatsce** [comment]
I think you should just fix the import manually for now, replace "com.spotify.sdk.android.authentication.RNSpotifyPackage" with "com.lufinkey.react.spotify.RNSpotifyPackage" in your MainApplication.java @nicolas-rohricht
