### ISSUE TITLE
Edit the readme file to add what the example does with a gif

### ISSUE THREAD

**Issue by Angelk90** [lufinkey/react-native-spotify#90]
Hi @lufinkey, It would be possible to add images or a gif or a video on YouTube in the readme file, to better understand what the module does, especially the example you have set. It would be of great interest to better understand the module.

**Comment by lufinkey** [comment]
I mean, I feel like it's fairly obvious what this module does, even from just the name. If you'd like to make a PR with some good gifs then feel free, but I just don't really feel that it's necessary.
