### ISSUE TITLE
RN Spotify Login Issues

### ISSUE THREAD

**Issue by srdesign-app** [lufinkey/react-native-spotify#93]
Hi @lufinkey! Thanks for this awesome repo and keeping it well-maintained.

Up till today, my app was running just fine, but I started getting the following message after clicking the "Login" button: 
```
RNSpotify.login was called with 0 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```
I have tried unlinking/uninstalling the dependencies mentioned in your README, doing a product > clean on XCode, even testing out an older version of my app, but nothing seems to work. 

Not sure if you know how to fix this, or maybe if you recently updated the repo to change `RNSpotify.login`, but any help would be greatly appreciated!

**Comment by lufinkey** [comment]
Can you post the code that's calling it? I have a default argument set for `RNSpotify.login` so you should be able to still call it with 0 arguments.

**Comment by lufinkey** [comment]
Are you importing RNSpotify through `import RNSpotify from `rn-spotify-sdk` or are you just calling it through `NativeModules.RNSpotify`? Because I make some changes to the RNSpotify object that don't happen if you don't import the file

**Comment by srdesign-app** [comment]
Yes I am importing it through `import Spotify from 'rn-spotify-sdk';`. Adding an empty object to the login method worked! The login code I use is identical to your example app.
