### ISSUE TITLE
More than one file was found with OS independent path 'lib/arm64-v8a/libgnustl_shared.so'

### ISSUE THREAD

**Issue by DontStealMyCodePls** [lufinkey/react-native-spotify#99]
I did install the module as you said in the README but when I try to build it to emulator the following error shows up

```* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/arm64-v8a/libgnustl_shared.so'
```
I did everything I could, I even reinitialized the app like 3-4 times and I couldn't get it to build without errors.

Platform: Android

**Comment by DontStealMyCodePls** [comment]
I fixed this error by adding these two lines in `android/app/build.gradle`:
```
exclude 'lib/arm64-v8a/libgnustl_shared.so'
exclude 'lib/x86_64/libgnustl_shared.so'
```
As I fixed this error I'm going to close this issue.

**Comment by DontStealMyCodePls** [comment]
I fixed this error by adding these two lines in `android/app/build.gradle`:
```
exclude 'lib/arm64-v8a/libgnustl_shared.so'
exclude 'lib/x86_64/libgnustl_shared.so'
```
As I fixed this error I'm going to close this issue.

**Comment by lufinkey** [comment]
Thank you so much for finding this. I'll add it to the README
